### ISSUE TITLE
Open search result context menu with menu key

### ISSUE THREAD

**Issue by JUSTIVE** [srwi/EverythingToolbar#101]
I think using the context menu key after I pressed the up/down arrow to focus on a list of searched items should pop up a context menu of the focused item, not the input search bar.

![image](https://user-images.githubusercontent.com/7118300/106077320-b1056500-6154-11eb-9f6c-9e4e2571ccb3.png)

**Comment by Horst12** [comment]
Here it works as it should.
What you have is only shown if I click with the right mouse button inside of the search field

**Comment by JUSTIVE** [comment]
Oh, the snap of what I'm experiencing in my environment.
after navigating through searched items with up/down arrows, the context menu key pops up on the search field.

**Comment by Horst12** [comment]
> 
> 
> Oh, the snap of what I'm experiencing in my environment.
> after navigating through searched items with up/down arrows, the context menu key pops up context menu on the search field.
**Confirmed for using the Shift-F10.**
I never use any key for the context menu, always the right mouse click.

**Comment by JUSTIVE** [comment]
I didn't know that Shift-F10 works as a context menu key, but good to hear that

**Comment by Coldblackice** [comment]
Currently, Shift-F10 brings up only a limited context menu, and it's also a context menu for the text/input box only, not the search results themselves. Ctrl-Shift-F10 is typically the keyboard shortcut used to bring up the traditional right-click context menu on file/folder selections (this works in Everything, as well).

Would it be possible to implement a keyboard shortcut (like Ctrl-Shift-F10) for accessing the right-click context menu of the highlighted search result items?

**Comment by srwi** [comment]
This feature will be available in the 1.3.1 release.
