### ISSUE TITLE
RTL languages support

### ISSUE THREAD

**Issue by do2or** [srwi/EverythingToolbar#15]
the toolbar isn't show correctly in RTL languages. 
![image](https://user-images.githubusercontent.com/10603352/95674277-ba73bd00-0bb7-11eb-93eb-071b0fcb4ed7.png)

**Comment by erez-c137** [comment]
I have a similar issue, where my Windows is in English but with RTL support and the toolbar is aligned to the left instead of the right. 
![image](https://user-images.githubusercontent.com/44322336/99205486-5a2cf800-27c1-11eb-9868-275f2267facb.png)

**Comment by stnkl** [comment]
It might be worth exploring https://github.com/dwmkerr/sharpshell#desk-band-extensions as an alternative to CSDeskBand for this.

**Comment by stnkl** [comment]
Yes, sorry about that. I have been working on that in #167 but was not able to fully fix it yet.

**Comment by do2or** [comment]
The menus in the software itself are also displayed in the opposite direction, instead of right to left, 
see the attached photo 
Thanks!
![EverythingToolbar0 7 1](https://user-images.githubusercontent.com/10603352/125465141-7148f3ca-e299-4b9d-a99b-7105432cf664.jpg)

**Comment by srwi** [comment]
Hi @Y-PLONI, thank for mentioning the problem again. I had another look and it was easier than expected to get the RTL alignment to work.

Regarding the deskband bug, I already tried a lot back then and I am not sure I'll find a better solution anytime soon. Therefore I'll call this issue done here as RTL languages are now fully supported on Windows 11.

**Comment by Y-PLONI** [comment]
@srwi 
Thank you very much!!!
When are you releasing an update?

**Comment by srwi** [comment]
Not sure yet. I might want to include one or two other fixes before releasing a new version. Maybe later this week!

**Comment by do2or** [comment]
I suggest to add the option to open search line in middle of the screen by
pressing Space key like Launchy or Listary

בתאריך יום ב׳, 23 בספט׳ 2024, 22:00, מאת Y-PLONI ***@***.***
