### ISSUE TITLE
Allow quicklook shortcut to be customized.

### ISSUE THREAD

**Issue by Karmah24** [srwi/EverythingToolbar#182]
Please add customization option to quicklook shortcut, many like be might have already mapped ctrl + space to something else.

**Comment by CainSakura** [comment]
`Ctrl + Space` was already mapped to MS Chinese Pinyin IME by default (switch between Chinese and English). So, at lease for Chinese users, QuickLook preview is not working. A temporary solution is to disable the `Ctrl + Space` hotkey in IME config.

**Comment by srwi** [comment]
Closing in favor of #351.
