### ISSUE TITLE
Search replacing doesn't work properly when enable IME

### ISSUE THREAD

**Issue by AioiLight** [srwi/EverythingToolbar#185]
**Describe the bug**
When Search replacing is enabled, it is not entered properly when IME is on.
I was happened in Japanese IME, but it could be happening in all of CJK.

**Steps to reproduce**
1. Enable "Replace start menu search"
1. Open EverythingToolbar once, make sure IME is turned on, and close it.
1. Press the Windows key. Enter any character to start EverythingToolbar.
1. Reproduce.

**Expected behavior**
In Japanese, typing "aa" should type "ああ".
Actually, typing "aa" will type "aあ".

I think that such a bug occurs because EverythingToolbar assigns `searchTermQueue` directly to the search string at ``EverythingToolbar\Helpers\ShortcutManager.cs``.

Until the IME decide the strings, they will not actually be entered into the search window.
So, if IME is on, the keyboard input needs to be emulated.

**Screenshots**
![image](https://user-images.githubusercontent.com/13918537/126024798-805d0eec-d7de-462e-9f99-318a29e9bc4b.png)

**Log file output**
<details>
<summary>Log output</summary>

```
2021-07-17 12:27:03.3053|INFO|EverythingToolbar started. Version: 0.7.1.0, OS: Microsoft Windows NT 10.0.19043.0|
2021-07-17 12:27:03.5563|INFO|Everything version: 1.4.1|
```
</details>

**Comment by srwi** [comment]
Closing in favor of meta issue #471.
