### ISSUE TITLE
Feature: An option to disable "Search as you type"

### ISSUE THREAD

**Issue by FrankAirs** [srwi/EverythingToolbar#253]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

"Search as you type" consumes a lot of CPU resources in my old PC.

### Proposed Solution

I advice to add an option to disable it. Then, when I press ENTER, the search starts. Thanks!

### Alternatives Considered

none

**Comment by srwi** [comment]
This option will be available in the next release!
