### ISSUE TITLE
Feature: Add option to hide icon from systray in Windows 11

### ISSUE THREAD

**Issue by ppvnf** [srwi/EverythingToolbar#255]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

In Windows 11 an icon is added to the system tray by EverythingToolbar, as Everything itself does. 

However, Everything has an option to hide the icon (while keeping Everything running in the background), but EverythingToolbar doesn't have a similar option.

### Proposed Solution

I would like EverythingToolbar to have a option similar to Everything for hiding the icon, maybe in the context menu that appears when you right click the systray icon itself, or in the Setup Assistant.

### Alternatives Considered

I think it would be useful to have a way to restore this setting, like clicking the .exe file. Maybe it would be good to also have a warning explaining how to do it.

**Comment by stnkl** [comment]
I like your suggestion and proposed solution. I would picture the behavior like this:

- The system tray icon should always be visible while EverythingToolbar is not pinned to the taskbar (so the user can always reach the setup assistant). In that case the option "Hide system tray icon" in the system tray context menu should be disabled.
- Once EverythingToolbar is pinned to the taskbar the option should be enabled to allow the user to disable the system tray icon. As you suggested a popup explaining how to reenable the icon should be displayed:
- Whenever the system tray icon is disabled it can be reenabled with a context menu option of the EverythingToolbar taskbar icon. Here is in example of Firefox using those context menu entries in its taskbar icon menu:
![grafik](https://user-images.githubusercontent.com/17520641/193455488-f9c06d4e-96d2-496f-a536-2022914f4c62.png)

**Comment by ThrowawayLawd** [comment]
windows 10 as well please :)

**Comment by srwi** [comment]
I had some time today and implemented this feature. The next version of EverythingToolbar will have an option to hide the system tray icon.
