### ISSUE TITLE
Bug: Opening a folder runs the same named executable instead

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [srwi/EverythingToolbar#303]
### Preflight Checklist

- [x] I have fully read the [README](https://github.com/stnkl/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

0.7.4

### Windows Version

Windows 10 version 21H2 LTSC

### Steps to reproduce

1. Put a folder.
2. Put an executable (.exe .bat .cmd) to the same directory.
3. Rename the executable to the folder name.
4. Search for the folder using EverythingToolbar.
5. Open the folder from the search results.

### Expected Behavior

Opens the folder in the Windows Explorer.

### Actual Behavior

Runs the executable near the folder.

### Screenshots

![bug](https://user-images.githubusercontent.com/84380947/213880580-1a19c5e1-7318-4c4d-adfc-634c3eac7af5.gif)

### Log output

2023-01-21 21:00:10.6245|INFO|EverythingToolbar started. Version: 0.7.4.0, OS: Microsoft Windows NT 10.0.19044.0|
2023-01-21 21:00:10.7785|INFO|Everything version: 1.4.1|

### Additional Information

Everything version: 1.4.1
Windows shell has the same issue.

**Comment by stnkl** [comment]
Very interesting find. Apparently this is the intended behavior of [Process.Start](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netframework-4.7). I implemented a workaround for that, which will be available in the next release (after 1.0.0).

**Comment by Kamilkampfwagen-II** [comment]
Thank you for your effort.

**Comment by srwi** [comment]
I had some time to look into it. It's a really unfortunate behavior of `Process.Start` that doesn't play well with third-party file browsers that some people are using. Unfortunately I broke the fix again with some changes related to third-party file browsers.
