### ISSUE TITLE
Use fixed config location

### ISSUE THREAD

**Issue by Destroy666x** [srwi/EverythingToolbar#313]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/stnkl/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Please save the user config in a better location than `C:\Users\User\AppData\Local\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj\10.0.19041.2486` - not sure why it's there and what the version numbers mean. There's already a different `user.config` in a slightly better dir `C:\Users\User\AppData\Local\EverythingToolbar\EverythingToolbar.Launche_Url_vaj5fmsnib0mkvub0wvxkpwbnuhugm51\1.0.0.0` but it doesn't have most of values. And the best location would be something like `%APPDATA%/EverythingToolbar` or `HKCU\SOFTWARE\EverythingToolbar` in registry which are standards.

Current location may cause problems with automated backups and stuff like that.

### Proposed Solution

Use either `%APPDATA%/EverythingToolbar` or `HKCU\SOFTWARE\EverythingToolbar` in registry as config location

### Alternatives Considered

^

**Comment by stnkl** [comment]
Hi @Destroy666x, thank you for the request. Unfortunately it is a little more complicated than just setting the file location, but definitely can be done. Currently EverythingToolbar uses the standard .net application settings which define the location based on the assembly information. In case of the deskband it actually relates to Windows explorer (hence the "Microsoft" with long version numbers).

As you suggested, it should go into `%APPDATA%\EverythingToolbar`, which is where the `rules.xml` file is created too.

**Comment by srwi** [comment]
Since version 1.4 the config is located at `%APPDATA%\EverythingToolbar\settings.ini`.
