### ISSUE TITLE
Crash on secondary screen with taskbar aligned to the right

### ISSUE THREAD

**Issue by kokanas** [srwi/EverythingToolbar#344]
### Discussed in https://github.com/srwi/EverythingToolbar/discussions/343

<div type='discussions-op-text'>

<sup>Originally posted by **kokanas** March  5, 2023</sup>
EverythingToolbar crashes when trying to open on secondary screen while the taskbar is aligned to the right edge of the screen.
Also there are general problems with EverythingToolbar's windows alignment when mixing vertical and horizontal taksbars on multiple screens. 

Im using Windows 11  [Version 10.0.22621.1344] and explorer patcher with windows10 taskbar style.

Firstly i open on right screen with horizontal taskbar works good then i try to open on left screen with right aligned taskbar and get a crash.

Log:

> 2023-03-05 13:11:22.9473|DEBUG|ToolbarLogger|Debug logging enabled.|
> 2023-03-05 13:11:23.0294|INFO|Launcher|EverythingToolbar Launcher 1.0.3.0 started. OS: Microsoft Windows NT 10.0.22621.0|
> 2023-03-05 13:11:27.9426|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
> 2023-03-05 13:11:28.0222|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|Calculating window position...|
> 2023-03-05 13:11:28.0222|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|taskbar.Edge: Bottom|
> 2023-03-05 13:11:28.0222|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|taskbar.Position: {X=0,Y=1410,Width=2560,Height=30}|
> 2023-03-05 13:11:28.0222|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|margin: 12|
> 2023-03-05 13:11:28.0222|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|windowSize: 1038, 1386|
> 2023-03-05 13:11:28.0222|DEBUG|EverythingToolbar.Launcher.Utils|Windows version: 10.0.22621.0|
> 2023-03-05 13:11:28.0222|DEBUG|EverythingToolbar.Launcher.Utils|taskbarAlignment: 0|
> 2023-03-05 13:11:28.0222|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|position: 12, position.Right: 1050, position.Top: 12, position.Bottom: 1398|
> 2023-03-05 13:11:34.5141|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|Calculating window position...|
> 2023-03-05 13:11:34.5141|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|taskbar.Edge: Right|
> 2023-03-05 13:11:34.5141|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|taskbar.Position: {X=-157,Y=0,Width=157,Height=1440}|
> 2023-03-05 13:11:34.5141|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|margin: 12|
> 2023-03-05 13:11:34.5141|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|windowSize: 1038, 1386|
> 2023-03-05 13:11:34.5141|DEBUG|EverythingToolbar.Launcher.SearchWindowPlacement|position: -2548, position.Right: -2729, position.Top: 12, position.Bottom: 1398|

This is my setup for clarity.
![ps](https://user-images.githubusercontent.com/7354849/222959881-bfba50c6-4a71-420d-9526-f4cca79e987d.png)
</div>

**Comment by srwi** [comment]
Thank you for the bug report. I implemented a fix which will be available in the next release!
