### ISSUE TITLE
Trigger QuickLook using space key

### ISSUE THREAD

**Issue by neoOpus** [srwi/EverythingToolbar#351]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

That would be also great is to see a thumbnail if it is an image (but just dismiss this if you prefer to) as I personally prefer the option on proposed solution.

### Proposed Solution

- The mouse select with one click an item on the list via single left-click and Spacebar open it in QuickLook and keep the search open obviously (the only issue is that this interferes with the search field and clicks over Spacebar add spaces to the search keywords)
- Double-Clicks Open it regularly.
- Ctrl and Shift work as in everything (and optionally see checkboxes like in explorer)

### Alternatives Considered

On hover some icons show up with some of the advanced (additional) interactions.

**Comment by srwi** [comment]
QuickLook is already supported with <kbd>Ctrl</kbd>+<kbd>Space</kbd>. But I plan to add an option "Automatically select first result" at some point. With that enabled QuickLook would not be possible, but with it disabled you could press <kbd>Down</kbd> to move the focus from the search box to the first result and open the preview window by pressing just <kbd>Space</kbd>.

**Comment by neoOpus** [comment]
Thank you, I wasn't aware of <kbd>Ctrl</kbd>+<kbd>Space</kbd> and it works, but it would be better if it is possible to have it preview the hovered file, so it is possible to scroll quickly and identify a file... the <kbd>Down</kbd> wouldn't be a good option a sort of soft focus (I don't know how to call it) that allows to keep the real focus on search field... I don't know if this makes sense to you.

**Comment by MMMMMoris** [comment]
> Thank you, I wasn't aware of Ctrl+Space and it works, but it would be better if it is possible to have it preview the hovered file, so it is possible to scroll quickly and identify a file... the Down wouldn't be a good option a sort of soft focus (I don't know how to call it) that allows to keep the real focus on search field... I don't know if this makes sense to you.

Why doesn't `Ctrl+Space ` work for me? Is this really applicapable?

**Comment by neoOpus** [comment]
Stephan,

Is it possible to make the opening of files use double click instead of one click, as the preview is hard and requires using keyboard to set focus over the file to be previewed (or maybe use the mouse to change focus instead of just highlighting but I am not sure about this one).

**Comment by neoOpus** [comment]
[**@MMMMMoris**](https://github.com/MMMMMoris) commented on [Aug 5, 2023, 5:23 AM EDT](https://github.com/srwi/EverythingToolbar/issues/351#issuecomment-1666451929 "2023-08-05T09:23:30Z - Replied by Github Reply Comments"):
> > Thank you, I wasn't aware of Ctrl+Space and it works, but it would be better if it is possible to have it preview the hovered file, so it is possible to scroll quickly and identify a file... the Down wouldn't be a good option a sort of soft focus (I don't know how to call it) that allows to keep the real focus on search field... I don't know if this makes sense to you.
> 
> Why doesn't `Ctrl+Space` work for me? Is this really applicapable?
> 
> _Originally posted by @MMMMMoris in https://github.com/srwi/EverythingToolbar/issues/351#issuecomment-1666451929_

Does QuickLook works for you on Explorer? have you tried to use keyboard arrows to pick the file

**Comment by srwi** [comment]
> Stephan,
> 
> Is it possible to make the opening of files use double click instead of one click, as the preview is hard and requires using keyboard to set focus over the file to be previewed (or maybe use the mouse to change focus instead of just highlighting but I am not sure about this one) ?

#409 

I'm currently working on that feature, but currently my time is limited so it might take some time.

**Comment by srwi** [comment]
https://github.com/srwi/EverythingToolbar/commit/f858bd66dd8b7d4b68130d533ed7f5b32d3f3900

**Comment by neoOpus** [comment]
This is a good thing as MS PowerToys comes with a similar feature to `QuickLook` called `Peek` and it uses Ctrl+Space by default, I didn't test it with ET yes as I reinstalled my machine but for the moment, `QuickLook` is more robust and allow previewing more formats.
