### ISSUE TITLE
No rounded corners

### ISSUE THREAD

**Issue by Zycelz** [srwi/EverythingToolbar#355]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Is there a way to remove the rounded corners on the Windows 11 version? I want it to be squared like the windows 10 version
![image](https://user-images.githubusercontent.com/105969023/227490285-5bcaad61-2f5e-4391-9dd3-54fb0a7a14bc.png)

### Proposed Solution

Make an option for it please.

### Alternatives Considered

Alternatives Considered

**Comment by srwi** [comment]
The corner radius of the search box can be customized by changing `TextBoxCornerRadius` in the theme file `Themes/Win11/Controls/TextBox.xaml` relative to your installation directory. EverythingToolbar needs to be restarted for the change to be visible. You can do so by restarting Windows explorer or rebooting your machine.

**Comment by Zycelz** [comment]
Thanks, do you know if it's possible to remove the corner radius of the normal win11 taskbar? (buttons etc)

**Comment by srwi** [comment]
Unfortunately I am not aware of a way to change that.

**Comment by Zycelz** [comment]
Oh, I assumed it was possible because I read the Windows 11 taskbar was made with xaml, and editing the EverythingToolbar xaml fixed the corners
![image](https://user-images.githubusercontent.com/105969023/227780378-8410f8c9-5cac-40a9-b863-3fe649e17121.png)
