### ISSUE TITLE
Add ability to clear shortcut

### ISSUE THREAD

**Issue by Lewis8379** [srwi/EverythingToolbar#357]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.0.3.0

### Windows Version

Windows 10 Enterprise 10.0.19045

### Steps to reproduce

1. Open the search window, click the 3 dots, click "preferences", click "change shortcut", enter a shortcut, and save.
2. Decide you don't want a shortcut
3. Do step 1 to bring up the window
4. Try to clear the window, by using backspace, escape, highlighting the text and deleting it, etc. The shortcut will become backspace, escape, etc

### Expected Behavior

Pressing escape or back should clear the field and remove the shortcut - who would use escape or backspace as a shortcut anyway?

### Actual Behavior

It is impossible to clear the shortcut

### Log output

Not relevant?

**Comment by srwi** [comment]
Thank you for the suggestion. In the next release it will be possible to clear the shortcut by pressing <kbd>Esc</kbd>.
