### ISSUE TITLE
Feature request : Please change the location of the Sort Order settings to location as shown

### ISSUE THREAD

**Issue by shodanx2** [srwi/EverythingToolbar#359]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

It is currently too many UI steps to make it to the sort order settings

### Proposed Solution

Please include as a button similar to the quick toggles

Or as part of the deployed everythingtoolbar flyout as depicted below

![image](https://user-images.githubusercontent.com/10621885/230690935-a9c08de7-c80d-4daf-ad86-dc0638978824.png)

### Alternatives Considered

In the flyout

or as a button on the toolbar

**Comment by srwi** [comment]
Thank you. I like your suggestions. I linked this ticket in #261 and will track it under that.
