### ISSUE TITLE
Feature request:  Set a default bookmark (example, start menu centric bookmark/filter)

### ISSUE THREAD

**Issue by shodanx2** [srwi/EverythingToolbar#360]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I am using everything toolbar as a start menu search alternative

I wish to limit the search terms to only applications in the normal application folders

Here is the "bookmark" I use for this in Everything

Note : I do not understand what is the difference between a bookmark and a filter at this time. 
I use Everything 1.5a and it seems it does not have filters ? Just bookmarks ? I am not sure

Anyway here is the search string I would like to prefix to all my start menu searches

<"%SystemRoot%\"|"%PROGRAMFILES%\"|"%PROGRAMFILES(X86)%\"|"%PROGRAMDATA%\"|"%userprofile%\" *.exe|*.bat|*.vbs|*.cmd|*.ps1>|<"%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\"|"%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs" *.lnk> !"%userprofile%\AppData\Local\Packages\Microsoft.Windows.Search"

If I paste this string in Everything toolbar before typing my search, it does exacly what I want

Here is for example, this string plus the word "7z"

![image](https://user-images.githubusercontent.com/10621885/230691442-f9743e1c-99a4-4bd7-ace8-35022899b045.png)

Just application and not 7z.exe from everywhere else on my hard drive, perfect !

When I press the start menu button, it should always search <default start menu search string> my_search_term_here

Note : I have currently enabled the "remember filter" option

However, if I type in a search from the start menu search, this filter is wiped out

example 

![image](https://user-images.githubusercontent.com/10621885/230691722-10d45d61-aae1-4112-bf80-468aaffbaf31.png)

### Proposed Solution

Ability to set a default search string

Ability to set a default search string per invokation method 

Example, invoke everythingtoolbar via startmenusearch,  then it prefixes the default start menu search string

or invoke everythingtoolbar via just clicking on it, then prefix with default search string (in my case, it would be an empty string)

### Alternatives Considered

There is no alternative that I could find, current behaviour is the search string is automatically erased.

I would keep a copy of the search string in my clipboard manager
Unfortunately, EverythingToolbar is unable to receive text from my clipboard manager

Demonstration of EverythingToolbar rejecting focus when the clipboard manager appears

![image](https://user-images.githubusercontent.com/10621885/230691934-195cd12d-f47a-47de-852e-9c19ce949fda.png)

**Comment by Horst12** [comment]
Bookmarks are not available for the toolbar and any other tool using the Everything SDK.
Thats not an error of the Toolbar but a limit of the current SDK.

**Comment by srwi** [comment]
You will have to define your search string as a new filter within Everything. The process is documented here: https://www.voidtools.com/support/everything/searching/#filters

Other than that your question was already answered here: https://github.com/srwi/EverythingToolbar/issues/186#issuecomment-890959204

In short: Add the filter, enable "Use Everything filters" option and "Remember filter" option. This will remember which filter was selected in EverythingToolbar (this refers to the tabs at the top of the search popup).

**Comment by shodanx2** [comment]
Thank you, now I understand the difference between Filters and Bookmarks, kind of.

At least now EverythingToolbar works as a start menu replacement 

Except for programs that are not files names such as Settings, Services, Optional Features, Remove program ... etc and the like.
I will try to create named batch file to fill in this game instead !

I have create a short guide on the voidtools everything forum explaining how to tune EverythingToolbar for use as a Start Menu replacement, I would say it currently works 90%

https://www.voidtools.com/forum/viewtopic.php?p=55588#p55588

**Comment by shodanx2** [comment]
Works great

Filter 

<"%SystemRoot%"|"%PROGRAMFILES%"|"%PROGRAMFILES(X86)%"|"%PROGRAMDATA%"|"%userprofile%" *.exe|*.bat|*.vbs|*.cmd|*.ps1>|<"%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"|"%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs" *.lnk> !"%userprofile%\AppData\Local\Packages\Microsoft.Windows.Search" !"C:\Windows\WinSxS" !"C:\Windows\servicing\LCU" !"C:\Windows\System32\DriverStore\" !"%PROGRAMFILES(X86)%\Microsoft Office\Updates\Download" !"%PROGRAMFILES%\Microsoft Office\Updates\Download"

Use Everything filters

Remember Filter

Set the Start Everything filter

Looks like this !

![image](https://user-images.githubusercontent.com/10621885/232274570-11505299-d28b-41b6-b3be-e99dc248659c.png)
