### ISSUE TITLE
Show file path in remaining space

### ISSUE THREAD

**Issue by shodanx2** [srwi/EverythingToolbar#365]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Often there are multiple files but it is not obvious which file is the good one, example this search for calc

![image](https://user-images.githubusercontent.com/10621885/231036058-2ce5e485-4ffc-4395-b9ad-a33859b5864f.png)

### Proposed Solution

I propose displaying the file path in the currently empty space between file name and file date as follows

![image](https://user-images.githubusercontent.com/10621885/231036147-0e3a081d-47c3-4729-9d76-766451fb3c58.png)

### Alternatives Considered

right click and view detail for each files until your find the right one

adding more exclusion filters to the search terms to reduce spurious results

Being able to right click on a file and "add this file path to the search exclusion paths" would be great !

Example here this file is

C:\Windows\WinSxS\amd64_microsoft-windows-calc_31bf3856ad364e35_10.0.19041.1_none_5faf0ebeba197e78\calc.exe

So I would add C:\Windows\WinSxS\amd64_microsoft-windows-calc* the exclusion path

`<"%SystemRoot%"|"%PROGRAMFILES%"|"%PROGRAMFILES(X86)%"|"%PROGRAMDATA%"|"%userprofile%" *.exe|*.bat|*.vbs|*.cmd|*.ps1>|<"%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"|"%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs" *.lnk> !"%userprofile%\AppData\Local\Packages\Microsoft.Windows.Search"`

would become (I changed it)

`<"%SystemRoot%"|"%PROGRAMFILES%"|"%PROGRAMFILES(X86)%"|"%PROGRAMDATA%"|"%userprofile%" *.exe|*.bat|*.vbs|*.cmd|*.ps1>|<"%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"|"%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs" *.lnk> !"%userprofile%\AppData\Local\Packages\Microsoft.Windows.Search" !"C:\Windows\WinSxS\" !"C:\Windows\servicing\LCU"`

NOTE I was not able to update these filters to demonstrate screenshot as I'm running Everything 1.5 and EverythingToolbar can't find %USERPROFILE%\AppData\Roaming\Everything\Filters-1.5a.csv

**Comment by srwi** [comment]
This feature already exists via the "view" option:

![grafik](https://user-images.githubusercontent.com/17520641/231242195-e0d91627-6bfe-4be4-a7e0-b0b2015033c2.png)

**Comment by shodanx2** [comment]
Works great thanks !!

I really like "Compact (Detailed)

![image](https://user-images.githubusercontent.com/10621885/232274465-ae51be1e-adf2-4cbc-a48f-fafd9e3fd773.png)
