### ISSUE TITLE
EverythingToolbar is unable to find filters-1.5a.csv for users of Everything 1.5a, even if instance name is set to 1.5a

### ISSUE THREAD

**Issue by shodanx2** [srwi/EverythingToolbar#367]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.0.3.0 please allow version copy and paste from About dialog

### Windows Version

Win10

### Steps to reproduce

Preference -> Use everything filter

Search for 
%USERPROFILE%\AppData\Roaming\Everything\Filters-1.5a.csv
however the file cannot be found due to filter allowing only files with the exact name "filters.csv"

### Expected Behavior

If instance name has been set to 1.5a

Program should look for the file 

%USERPROFILE%\AppData\Roaming\Everything\Filters-1.5a.csv

by default and filename filter should be something like
filters*.csv or filters-1.5a.csv or simply *.csv

### Actual Behavior

Program unable to find filters-1.5.csv

### Log output

Unable to provide as it does not ask again once provided

I am also now unable to update my filters after changing them in everything

**Comment by srwi** [comment]
The file can be selected by changing the filter. I will not update the filters because the name 'filters-1.5a.csv' is only a temporary name while version 1.5 is in alpha.

![grafik](https://user-images.githubusercontent.com/17520641/231240579-62fa78ca-b462-488f-a7c9-1040bbdb1da4.png)

**Comment by shodanx2** [comment]
Could you make the filter search filters*.csv, or even *.csv ?

Is there a way to restart EverythingToolbar other than logout/login ? 

I tried removing toolbar/ re-adding it, but it doesn't reload the toolbar.

I tried disable and re-enable "use everything filters" but it had no effect, it would be great if that action caused the toolbar to re-read the filters.csv file

**Comment by Horst12** [comment]
Whats the problem to logout/login once to get the question where the filters are stored ?
You only have to do this once after an update.
Using *.csv is a strange idea as Everything has many csv files in the same place than filters.csv

**Comment by srwi** [comment]
@shodanx2 You can locate your user settings file at `%LOCALAPPDATA%\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj\<Explorer version number>\user.config` and either remove the file entirely to reset EverythingToolbar settings or change/remove the `filtersPath` setting in there directly.

**Comment by shodanx2** [comment]
@srwi 
Thank you

I did find a file called 

C:\Users\shodan\AppData\Local\Microsoft_Corporation\DefaultDomain_Path_letvcrhmovxkwhkcw5vzjcoa5azw22uj\10.0.19041.2311\user.config

It contained the following 

While setting it up I was a little confused and pointed it to a copy of the file .old
I was wondering why I was not able to update the filters no matter what I did, even restarts

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="EverythingToolbar.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <EverythingToolbar.Properties.Settings>
            <setting name="filtersPath" serializeAs="String">
                <value>C:\Users\shodan\AppData\Roaming\Everything\Filters-1.5a.csv.old</value>
            </setting>
            <setting name="isUpgradeRequired" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="instanceName" serializeAs="String">
                <value>1.5a</value>
            </setting>
            <setting name="popupSize" serializeAs="String">
                <value>947,680</value>
            </setting>
            <setting name="isReplaceStartMenuSearch" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="isRememberFilter" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="isShowResultsCount" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="isShowQuickToggles" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="isThumbnailsEnabled" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="isImportFilters" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="isHideEmptySearchResults" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="isEnableHistory" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="isMatchCase" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="itemTemplate" serializeAs="String">
                <value>CompactDetailed</value>
            </setting>
        </EverythingToolbar.Properties.Settings>
    </userSettings>
</configuration>
```

 
Here is my latest "Start Everything" filter  BTW

Name,Case,Whole Word,Path,Diacritics,Prefix,Suffix,Ignore Punctuation,Ignore Whitespace,Regex,Search,Columns,Sort,Descending,View,Macro,Key
"Start Everything",0,0,0,0,0,0,0,0,0,"<""%SystemRoot%""|""%PROGRAMFILES%""|""%PROGRAMFILES(X86)%""|""%PROGRAMDATA%""|""%userprofile%"" *.exe|*.bat|*.vbs|*.cmd|*.ps1>|<""%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs""|""%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs"" *.lnk> !""%userprofile%\AppData\Local\Packages\Microsoft.Windows.Search"" !""C:\Windows\WinSxS\"" !""C:\Windows\servicing\LCU""","","",0,,,

**Comment by shodanx2** [comment]
I confirm I can now update filters in everything 

In EverythingToolbar I only need to Disable then re-enable "Use Everything Filters"
![image](https://user-images.githubusercontent.com/10621885/232274407-59dc9498-e934-4cb9-a4fc-6ac2f09ef16e.png)


Then unset and re-set the filter 

![image](https://user-images.githubusercontent.com/10621885/232274414-5e87126b-b42e-4734-8ef9-d2c4b324e013.png)


And the filter gets updated

Here is my latest "Start Everything" filter

<"%SystemRoot%"|"%PROGRAMFILES%"|"%PROGRAMFILES(X86)%"|"%PROGRAMDATA%"|"%userprofile%" *.exe|*.bat|*.vbs|*.cmd|*.ps1>|<"%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"|"%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs" *.lnk> !"%userprofile%\AppData\Local\Packages\Microsoft.Windows.Search" !"C:\Windows\WinSxS" !"C:\Windows\servicing\LCU" !"C:\Windows\System32\DriverStore\" !"%PROGRAMFILES(X86)%\Microsoft Office\Updates\Download" !"%PROGRAMFILES%\Microsoft Office\Updates\Download"
