### ISSUE TITLE
It's hoped that after fixing the taskbar icon, the tray icon can be hidden, as displaying both icons is redundant.

### ISSUE THREAD

**Issue by nljxlove** [srwi/EverythingToolbar#369]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

It's hoped that after fixing the taskbar icon, the tray icon can be hidden, as displaying both icons is redundant.

### Proposed Solution

It's hoped that after fixing the taskbar icon, the tray icon can be hidden, as displaying both icons is redundant.

### Alternatives Considered

It's hoped that after fixing the taskbar icon, the tray icon can be hidden, as displaying both icons is redundant.

**Comment by srwi** [comment]
Duplicate of #255.
