### ISSUE TITLE
Allow copying version number from about dialog

### ISSUE THREAD

**Issue by shodanx2** [srwi/EverythingToolbar#372]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

This text cannot be copied and pasted

![image](https://user-images.githubusercontent.com/10621885/232385304-e75f9244-71c2-45b6-9978-baaa1dcbff8a.png)

### Proposed Solution

Make it selectable and copiable test

### Alternatives Considered

reading the text and typing it manually in the bug report form

**Comment by srwi** [comment]
Thank you for the suggestion. It will be possible to select/copy the version number in the next release!

**Comment by shodanx2** [comment]
Sweet !
Also, anything you like hearing about in a bug report, that's the place to put it. 
User are going to grab it along with the version number and paste it in the report
