### ISSUE TITLE
Everything Toolbar does not call correct File Handler when Default File Handler has ben Changed 

### ISSUE THREAD

**Issue by Foxxsayy** [srwi/EverythingToolbar#373]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.0.3.0

### Windows Version

Windows 11 Home, Version 22H2

### Steps to reproduce

Click on any folder in the Everything Search Toolbar to replicate.

If the default file manager has been changed, clicking on a folder in the Everything Search Toolbar will not open it. For instance, if a user has Directory Opus set to be their default file manager, clicking a folder in the everything searched for bar still opens it in Windows File Explorer.

I confirmed that the base Everything program works as expected will call the default file handler. My guess is that the Everything Search Toolbar is currently coded to call Windows File Explorer explicitly rather than calling for the default file manager.

### Expected Behavior

When a folder is clicked/opened via the Everything Toolbar, open it with the **default** file manager. [e.g., Directory Opus, Total Commander, etc.]

### Actual Behavior

When a folder is clicked/opened via the Everything Toolbar, it opens in Windows File Explorer regardless of default file manager.

### Screenshots

N/A

### Log output

N/A

### Additional Information

N/A

**Comment by Horst12** [comment]
Make a simple rule for folders and you have it.
My rule for Total Commander looks like this
![Screenshot - 18 04 2023 , 22_11_05](https://user-images.githubusercontent.com/38587340/232893951-231bd267-cbb0-4756-94df-e52e35ec07f2.png)

**Comment by Foxxsayy** [comment]
> Make a simple rule for folders and you have it.)

**Comment by Foxxsayy** [comment]
> Make a simple rule for folders and you have it.

@Horst12 Thanks for the tip! that's a good workaround. Can I see the rest of what you wrote for TC Folder? I'm good with Boolean operators, but I'm not great with RegEx or CMD or Path Syntax. 

For the RegEx, what does the ^.&$ mean? (It looks like the strings you have in place for TC, XY, and Edit are specifying the file types to use with that command?) In the Command section, it looks like a standard <FilePath_to_Program> <Options_go_here> program call, but I'm not sure what the _/a /o /s_  and %file% modifiers do?

**Comment by srwi** [comment]
I tried fixing this a while ago already. I think this time I did it correctly. Thanks for reminding me to look into it again!

**Comment by Foxxsayy** [comment]
> I tried fixing this a while ago already. I think this time I did it correctly. Thanks for reminding me to look into it again!

Thanks! I assume the fix will be in the next release?

**Comment by srwi** [comment]
Yes, exactly.
