### ISSUE TITLE
toolbar is not working

### ISSUE THREAD

**Issue by huai168an** [srwi/EverythingToolbar#376]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.0.5

Everything version: V1.4.1.1022 (x64)

### Windows Version

win7 pro service pack 1  x64

### Screenshots

![捕获](https://user-images.githubusercontent.com/52577307/234173606-cdd9dada-4099-4473-baf2-5d554ad82ea1.PNG)

### Log output

2023-04-25 12:00:22.5509|INFO|Launcher|EverythingToolbar Launcher 1.0.5.0 started. OS: Microsoft Windows NT 6.1.7601 Service Pack 1|
2023-04-25 12:10:48.6047|INFO|Launcher|EverythingToolbar Launcher 1.0.5.0 started. OS: Microsoft Windows NT 6.1.7601 Service Pack 1|
2023-04-25 12:12:08.2143|INFO|Launcher|EverythingToolbar Launcher 1.0.5.0 started. OS: Microsoft Windows NT 6.1.7601 Service Pack 1|
2023-04-25 12:14:08.2802|INFO|Launcher|EverythingToolbar Launcher 1.0.5.0 started. OS: Microsoft Windows NT 6.1.7601 Service Pack 1|

context menu and enable it，but....

System.Windows.Markup.XamlParseException: 对类型“EverythingToolbar.Behaviors.ThemeAwareness”的构造函数执行符合指定的绑定约束的调用时引发了异常。 ---> System.TypeLoadException: 找不到 Windows 运行时类型“Windows.UI.ViewManagement.UISettings”。 ---> System.PlatformNotSupportedException: 此平台上不支持操作。
   --- 内部异常堆栈跟踪的结尾 ---
   在 EverythingToolbar.Behaviors.ThemeAwareness..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   在 EverythingToolbar.ToolbarControl..ctor() 位置 C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\ToolbarControl.xaml.cs:行号 20
   在 CSDeskBand.Deskband..ctor() 位置 C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\Deskband.cs:行号 24

**Comment by srwi** [comment]
Hello @huai168an, which version of .NET Framework is installed on your machine? Here is how to check which version is installed: https://user-images.githubusercontent.com/14129585/104021832-ff36e080-5206-11eb-9f5f-10e4381992f9.jpg

**Comment by huai168an** [comment]
![图片](https://user-images.githubusercontent.com/52577307/234718800-85379141-aeaa-4845-a566-a081fdfc9057.png)

**Comment by huai168an** [comment]
![图片](https://user-images.githubusercontent.com/52577307/235015942-b732cd15-0aa8-46cb-b890-655d89582d72.png)
