### ISSUE TITLE
Feature: Reset Quick Toggles Every Time

### ISSUE THREAD

**Issue by KaiHuaDou** [srwi/EverythingToolbar#380]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

In most situations, I don't want to open any quick toogles.
In some situations, I need to open one or two quick toogles.

But when i change from "some situations" to "most situations", I need to close quick toogles on by one.
And I need to switch between "some situations" and "most situations" for a lot of times.

### Proposed Solution

Add a options called "Reset quick toogles every time"
If I checked it, the quick toogles will reset to default every time I open EverythingToolbar.

### Alternatives Considered

Another solution is add a button to reset 4 quick toogles at once.

**Comment by Horst12** [comment]
Create Everything filters with you required settings.
