### ISSUE TITLE
[Packaging] Scoop Distribution

### ISSUE THREAD

**Issue by TayouVR** [srwi/EverythingToolbar#382]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I generally use [scoop](https://scoop.sh/) to install software on windows, I know i could use Chocolatey or winget, but I would prefer scoop.

### Proposed Solution

PR the necessary manifest file to [Scoop Extras Bucket](https://github.com/ScoopInstaller/Extras/) or another scoop bucket.

### Alternatives Considered

using choco or winget, but I would really prefer scoop.

**Comment by srwi** [comment]
Hi @TayouVR and sorry for the late reply. Are you aware of any automated solutions to release to Scoop?

**Comment by TayouVR** [comment]
scoop can automatically fetch new releases from github releases or ci if the package manifest is setup that way.
I have not created any scoop packages myself, so I'm not the most knowledgeable about that.
If I were to create that manifest myself i would take a look at the games/prismlauncher and versions/prismlauncher-git packages respectively and kinda copy that a little (as I'm involved with that project). Otherwise, scoop has documentation here: 
https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests
https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate

**Comment by TayouVR** [comment]
thank you! I may try this out shortly

**Comment by srwi** [comment]
It was merged into Extras now.
