### ISSUE TITLE
Have the shortcut key toggle the window instead of only opening the toolbar

### ISSUE THREAD

**Issue by roblet404** [srwi/EverythingToolbar#392]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

The shortcut opens everything toolbar but to close you have to click out of the toolbar or on another program to loose focus.

### Proposed Solution

Changing the shortcut key to a toggle function instead of only being able to use it to open the toolbar.

### Alternatives Considered

none

**Comment by Horst12** [comment]
Thats allready working as you want.
The shortcut in the taskbar toggles  for me.
______________________________________________________
Windows 11 Home x64 Version 22H2 (OS Build 22621.1778)
Everything 1.5.0.1347a (x64), Everything Toolbar 1.1.1

**Comment by srwi** [comment]
> Thats allready working as you want. The shortcut in the taskbar toggles for me.

The OP is refering to the keyboard shortcut that brings up the search window.

@roblet404 Thanks for pointing it out. It was once working in the past but I broke something. I implemented a fix for it.
