### ISSUE TITLE
Cant download (v1.1.1) as Win 11 defender smartscreen doesnt know if it is safe... request if you could clear this...

### ISSUE THREAD

**Issue by squidfire** [srwi/EverythingToolbar#393]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.1.1

### Windows Version

Windows 11

### Steps to reproduce

![image](https://github.com/srwi/EverythingToolbar/assets/56499546/04dceef4-7f50-4335-b3a3-890862d200ac)

### Expected Behavior

cant donwload

### Actual Behavior

cant download, blocked, defender smartscreen

### Screenshots

 
![image](https://github.com/srwi/EverythingToolbar/assets/56499546/5544b422-8c01-405d-a45d-a324e86b2138)

### Log output

 
![image](https://github.com/srwi/EverythingToolbar/assets/56499546/d0d9fc48-f861-4ff2-9ae8-61c4a568d2cd)

**Comment by Horst12** [comment]
Normaly you can allow Defender by setting the option ... behind the first line
and later say Keep.
If your machine is not under your control the Author can't help.
You can wait some time, after the file was downloaded by more poeble
you may be able to also download it.

**Comment by squidfire** [comment]
Thanks
But please include the version under voidtools where the install.manufests the same issue

+98201 60074 call only if urgent, else text or email
________________________________

**Comment by srwi** [comment]
I honestly don't see any need for action since the SmartScreen popup is just a minor inconvenience during installation and not really worth the additional overhead of manually submitting the installer for each release. Sorry to disappoint.

**Comment by squidfire** [comment]
that’s fine.
i did an install by doing the continue anyway option.
it does not matter now.
everything doesn’t search everything. I was interested in content search as well.
i will go with X1 Search. Fast enough for me and does everything, more than Everything.

+98201 60074 call only if urgent, else text or email
________________________________
