### ISSUE TITLE
Support auto-hiding taskbar

### ISSUE THREAD

**Issue by TheRealBix** [srwi/EverythingToolbar#4]
With taskbar hiding enabled, clicking somewhere on the taskbar keep it from hiding. This is normal behaviour.

But clicking inside searchbox doesn't trigger this behaviour and taskbar hides while typing (if cursor is moved away).

Clicking on the taskbar to hold it then clicking inside the searchbox also release the taskbar.

**Comment by stnkl** [comment]
Good find. I didn't do any testing with auto-hiding taskbar. I'll see what I can do.

**Comment by stnkl** [comment]
I implemented a partial fix for this problem. As long as the mouse is over the taskbar it will not auto-hide. I couldn't find a clean solution for keeping it visible when the mouse is not over the taskbar.

**Comment by jacksongoode** [comment]
Bumping this fix!

**Comment by stnkl** [comment]
@jacksongoode I've actually spent hours working on this a few days ago but really can't make it work. I found a way to fix this but it causes other problems that prevent me from releasing the fix. See #167. Really need some help here.

**Comment by Fefedu973** [comment]
the search box need to be raised to not be hidden behind the taskbar and the task bar must stay opened

**Comment by srwi** [comment]
The window positioning has been fixed in #434. For the taskbar staying open it's not that easy as I mentioned before. I think a good compromise would be to force the user to use the search icon rather than the embedded search box whenever the taskbar is set to auto-hide.
