### ISSUE TITLE
NVIDIA GPUs Clocks Stuck

### ISSUE THREAD

**Issue by BiRaitBec** [srwi/EverythingToolbar#402]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

 1.1.1.0

### Everything Version

1.4.1.1024

### Windows Version

22621.1848

### Steps to reproduce

Check GPUs Clocks and GPUs Memory clocks at idle with no program running and with proper idle clocks, then enable everything toolbar so that it stays only in the tray and clocks should get stuck to a point where it is usually used for heavy gpu app running in the foreground. 

Keeping everything toolbar active at desktop usage even if you don't even run it for days pushes your gpu card too much constantly and raises your gpu power consumption.

### Expected Behavior

Having everything toolbar on the tray or everything not used and still seeing the same clocks as idle desktop usage, not constant stuck clocks as if there was an heavy benchmarking gpu application running.

### Actual Behavior

GPU is pushed to a constant clock when the programs of everything are running, even if unused, and they should not require constant high clocks cause they are not graphically intensive applications.

### Screenshots

<img width="743" alt="2023-06-21 06_56_19-NVIDIA GeForce Overlay DT" src="https://github.com/srwi/EverythingToolbar/assets/33075619/1e52288a-a76d-40c2-9ab9-f92d9d618de9">
<img width="688" alt="2023-06-21 06_56_55-NVIDIA GeForce Overlay DT" src="https://github.com/srwi/EverythingToolbar/assets/33075619/37e4905f-bb00-4879-b156-0e10220fade5">

### Log output

[EverythingToolbar.log](https://github.com/srwi/EverythingToolbar/files/11812361/EverythingToolbar.log)

**Comment by srwi** [comment]
Hi @BiRaitBec, unfortunately I can not reproduce the problem. On my machine (RTX 2080 S) the idle clock is at 300MHz and only sometimes ramps up during opening or closing animations of EverythingToolbar.

It is hard to say what could be causing this.  Possibly there is some configuration on your computer that gives higher priority to EverythingToolbar? Does the same happen for other applications that use hardware acceleration (e.g. Spotify or a web browser)?
