### ISSUE TITLE
[UI Enhancements] Cluttered "sort by" menu

### ISSUE THREAD

**Issue by Mitia99** [srwi/EverythingToolbar#405]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

![Screenshot 2023-06-24 145808](https://github.com/srwi/EverythingToolbar/assets/56766778/31dc1734-f4a4-4b80-afcb-f224d8244222)

### Proposed Solution

Merge items with the same name (Name, Size, Type...) and add a section for ascending/descending
![Screenshot 2023-06-24 145529](https://github.com/srwi/EverythingToolbar/assets/56766778/3976a3d6-0d08-401e-a2f8-94a4cce70a5a)

**Comment by user1823** [comment]
I second this request. Everything also uses a menu similar to the one in the Proposed Solution.

![image](https://github.com/user-attachments/assets/e18dd97e-ae53-4735-bfb3-a9f5215cd0b6)
