### ISSUE TITLE
Expand environment variable

### ISSUE THREAD

**Issue by Mitia99** [srwi/EverythingToolbar#408]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

 1.1.1.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 11 Pro 22H2

### Steps to reproduce

1. Open EverythingToolbar
2. Search %LOCALAPPDATA%\

### Expected Behavior

Display results like Everything
![image](https://github.com/srwi/EverythingToolbar/assets/56766778/41196059-fb9e-430d-8b55-3cc5f8c5abed)

### Actual Behavior

No search results

### Screenshots

![image](https://github.com/srwi/EverythingToolbar/assets/56766778/876f5167-2c99-4613-86b9-81dff63fbf9a)

### Log output

2023-07-03 13:01:59.3568|INFO|Launcher|EverythingToolbar Launcher 1.1.1.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2023-07-03 13:26:02.3938|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

### Additional Information

**Expand environment variable** must be enabled in order to display results from Everything (**Tools** menu/**Options**/**Search** tab on the left)
![image](https://github.com/srwi/EverythingToolbar/assets/56766778/3ffbb4fb-57da-4a21-80c5-96fd99fab10c)
**Exclude hidden files and folders** must be disabled (**Tools** menu/**Options**/**Exclude** tab on the left)
![image](https://github.com/srwi/EverythingToolbar/assets/56766778/ac91853d-46f3-4288-942b-9989ef030d34)

**Comment by Horst12** [comment]
Works fine using Everything version 1.5

![Screenshot - 03 07 2023 , 16_26_02](https://github.com/srwi/EverythingToolbar/assets/38587340/e3a483c9-e1bb-4c54-a856-c122eceb370c)

______________________________________________________
Windows 11 Home x64 Version 22H2 (OS Build 22621.1928)
Everything 1.5.0.1351a (x64), Everything Toolbar 1.1.1

**Comment by Mitia99** [comment]
@Horst12 Can you try with Everything 1.4.1.1024 (x64) ?

I prefer using stable builds.

Thanks,

**Comment by Horst12** [comment]
Then you miss all the much better functions and performance of the 1.5.
This works stable, and I don't see more problems with the alpha as the 1.4
reading the forums all the time.

**Comment by Mitia99** [comment]
@srwi I tried with Everything 1.5a and it displays results.

So it is definitely an issue with 1.4.

It would be great if you can fix it cause many users are on stable builds and we don't know when 1.5a will have a stable release.

Thanks for investigating,

**Comment by srwi** [comment]
EverythingToolbar behaves as expected currently by not expanding environmental variables (it is not enabled by default in Everything 1.4).

As to not bloat EverythingToolbar with every possible option that exists in Everything itself I would rather not implement that feature, given there is a way to still get the behavior by using 1.5a.
