### ISSUE TITLE
Add option for single click to select and double click to open

### ISSUE THREAD

**Issue by nochlab1** [srwi/EverythingToolbar#409]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

When trying to use the quicklook feature i have to first right click to select the item without opening it then click esc to close context menu and then use the quick look feature 

### Proposed Solution

Have a option that will use quicklook on the item that is highlighted by mouse currently instead of by program.

or another option where you have to double click or use the enter key to actually open the file and not select it (like the everything program),.

Thanks

### Alternatives Considered

I couldnt find any

**Comment by Horst12** [comment]
To open a file or execute it is the standard behavior of the toolbar if you enter or double-click a results' entry.
You can also make rules what programs are used for certain extensions.

**Comment by nochlab1** [comment]
> To open a file or execute it is the standard behavior of the toolbar if you enter or double-click a results' entry. You can also make rules what programs are used for certain extensions.
> 
> Windows 11 Home x64 Version 22H2 (OS Build 22621.1928) Everything 1.5.0.1351a (x64), Everything Toolbar 1.1.1

Ye but i want a option that it should only open with a double click or enter and not a single click

**Comment by srwi** [comment]
Hi @nochlab1, I am having problems reproducing the behavior you are describing. For me QuickLook behaves as expected. Let me describe the steps I take to preview different search results in QuickLook:

1. Search something in EverythingToolbar
2. Pressing Ctrl+Space previews the first search result
3. Press the down arrow on the keyboard
4. Pressing Ctrl+Space again previews the second search result

You might be confusing the keyboard focus, indicating which search item will be displayed in QuickLook, and the mouse hover highlight, which is just a visual cue. Opening the context menu of an item will set the keyboard focus to it, causing it to be the target for QuickLook once you press Ctrl+Space again.

Could you please double check if the behavior is consistent with what I described above? If not please provide me with some information that would allow me to further look into the problem (Windows version, EverythingToolbar version, QuickLook version, etc.)

**Comment by srwi** [comment]
Okay, I understand the problem now. In that case you are correct, that an option to change the behavior to select on single click and open on double click would solve that problem. Thank you.

**Comment by YiZhiRikka** [comment]
same
