### ISSUE TITLE
Option to set position for pop up search menu to centered

### ISSUE THREAD

**Issue by matt-derrick** [srwi/EverythingToolbar#411]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Just a thought, but it would be convenient if there was an option to set the search box that appears when clicking on the magnifying glass icon to centered, instead of appearing in the left corner of the screen in Windows 10.

If you're using windows 11, this isn't an issue, obviously. Everything Toolbar centers the menu properly.

If you're using the app 'Start11' by stardock in windows 10 though, you can center the start menu and icons like it is in windows 11. But, even with Start11, Everything toolbar's search that appears when clicking the taskbar icon still appears on the left corner. That's only in windows 10 though.

Example screen shot in windows 10 using the Start11 app:
https://i.imgur.com/1WRU1FW.png

### Proposed Solution

Add an option to the settings to 'center' the pop up menu or keep it aligned to the left (for those not using Start11 or TaskbarX or a similar program).

### Alternatives Considered

Not sure? I appreciate the consideration tho

**Comment by srwi** [comment]
Hi @matt-derrick, I added an option `isForceCenterAlignment` that will force the search window to be center-aligned. I don't want to add it to the settings menu to prevent bloat since this is a rather niche requirement. The option can be set in the `user.config` file for EverythingToolbar (unfortunately the config location currently varies a bit, see #313):

            <setting name="isForceCenterAlignment" serializeAs="String">
                <value>True</value>
            </setting>

This will be available in the next release (no ETA yet).

**Comment by srwi** [comment]
EverythingToolbar settings moved to a fixed location `%APPDATA%\EverythingToolbar\settings.ini` in version 1.4.0. So you will have to set that setting in there instead. 

It's possible that Start11 manages the taskbar alignment with it's own setting. EverythingToolbar respects the regular system setting so you might have to check that again.

**Comment by srwi** [comment]
My bad, the name changed to `IsForceCenterAlignment` starting with an uppercase `I`. With that it should work. 🙂

**Comment by Pacha-io** [comment]
Need some help.
This isn't working for me, look at this image:
![image](https://github.com/user-attachments/assets/9064099b-38d9-4c11-b807-17f7859ac42b)

**Comment by Pacha-io** [comment]
Hello @matt-derrick it was my mistake. I missed an "n" on the word alignment but @srwi noticed that in another comment that I posted.

But thank you for your attention! 😁
