### ISSUE TITLE
Can't delete file - "Delete" button on keyboard

### ISSUE THREAD

**Issue by Mitia99** [srwi/EverythingToolbar#416]
### Preflight Checklist

- [x] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.2.0

### Everything Version

1.5.0.1352a (x64)

### Windows Version

Windows 11 Pro 22H2 22621.1992

### Steps to reproduce

1. Search a file
2. Click "Delete" button on keyboard

### Expected Behavior

Delete the file

### Actual Behavior

Nothing happens

### Additional Information

Maybe it is more a feature request/enhancement than a bug.
I don't know if it should be supported on EverythingToolbar 1.1.1

It's supported on Everything 1.5

**Comment by Horst12** [comment]
Only the context menu entry works in the toolbar.
... Show more options
Delete
______________________________________________________
Windows 11 Home x64 Version 22H2 (OS Build 22621.1992)
Everything 1.5.0.1352a (x64), Everything Toolbar 1.1.1

**Comment by srwi** [comment]
Closing in favor of #316 and #414.
