### ISSUE TITLE
Mica visual effects? 

### ISSUE THREAD

**Issue by momoe** [srwi/EverythingToolbar#418]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Everything Toolbar naturally defaults to the system Ligh/Dark themes, which is okay. However does not have access to the Mica visual effects in the toolbar. 

### Proposed Solution

MicaForEveryone is a free opensource Github that does a great job of enabling Mica and other window UI effects for many different apps, but was not able to get EverythingToolbar.Launcher to work with it. https://github.com/MicaForEveryone/MicaForEveryone

### Alternatives Considered

If there's a more native way to integrate W11's mica features would be nice, but would probably limit backwards compatibility with other OS's

**Comment by srwi** [comment]
Which Windows version are you running? EverythingToolbar uses the Mica window style as long as it is not globally disabled in your system settings. Could you show a screenshot of what it looks like for you please?

**Comment by momoe** [comment]
![Untitled](https://github.com/srwi/EverythingToolbar/assets/19848666/af17326f-aa68-496b-8ddf-c2330ec166ea)

**Comment by momoe** [comment]
Apologies, `winget` was pulling v0.8.01 not the most current version. This is now marked as resolved. Ty for your time .
