### ISSUE TITLE
Allow only the icon to show in vertical taskbar orientation (W10)

### ISSUE THREAD

**Issue by piebaker** [srwi/EverythingToolbar#423]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

The current taskbar shows a preview of the typed word while the taskbar is vertical (see image), it would look a lot better with the option of a pure icon like in the horizontal view
![image](https://github.com/srwi/EverythingToolbar/assets/73162560/f9cb033a-6508-4a4c-a2df-bacc5e62c009)

### Proposed Solution

Allow purely an icon to show while the taskbar is vertical

### Alternatives Considered

N/A

**Comment by srwi** [comment]
Hi @piebaker, you should be able to use the search icon by slimming down your taskbar a little more. There is a width threshold where the search bar converts into the search icon button. I believe the threshold is 70px.

**Comment by FledaJohansson** [comment]
Based on #627 , if you start EverythingToolbar (right-click the taskbar and select EverythingToolbar from the Toolbars context menu) while having "Automatically hide taskbar in desktop mode" on, afterward the icon would not expand into a search bar no matter how wide you stretch your taskbar, even with "Automatically hide taskbar in desktop mode" off. If you restart the computer, the icon would turn into the search bar like normal though, so you would have to redo all steps above. I just don't turn off my PC so it's not much of a problem.
