### ISSUE TITLE
unable to use ctrl+space to open up Quicklook to preview

### ISSUE THREAD

**Issue by MMMMMoris** [srwi/EverythingToolbar#429]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.2.0

### Everything Version

 1.4.1.1024 (x64)

### Windows Version

Windows 11 22621.2070

### Steps to reproduce

Just open up everythingToolbar and press up and down arrow key to select items, and then press ctrl +space key, no preview of Quicklook was shown.

### Expected Behavior

Press up and down arrow key to select items, and then press ctrl +space key, preview of Quicklook shows.

### Actual Behavior

Just open up everythingToolbar and press up and down arrow key to select items, and then press ctrl +space key, no preview of Quicklook was shown.

### Screenshots

![image](https://github.com/srwi/EverythingToolbar/assets/63332824/22ba0948-f6d9-499f-b77a-f3ecb69a0392)

### Log output

2023-08-05 17:03:09.0981|INFO|Launcher|EverythingToolbar Launcher 1.2.0.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2023-08-05 17:11:24.7453|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-08-05 17:14:16.9968|INFO|EverythingToolbar.Helpers.FilterLoader|Filters.csv could not be found at C:\Users\moris\AppData\Roaming\Everything\Filters.csv|

**Comment by srwi** [comment]
Hello @MMMMMoris, which version of QuickLook are you using? I just tried it with the [latest version](https://github.com/QL-Win/QuickLook/releases/tag/3.7.3) and it seems to be fully functional. Does QuickLook work in Windows Explorer by pressing <kbd>Space</kbd> while having a file selected?

**Comment by MMMMMoris** [comment]
> 
Yes, Quicklook works well  in Windows Explorer by pressing Space while having a file selected, as well as in Everything. It is just not functional in EvrythingToolBar. Mine is latest version downloaded from github,installed with msi package.
![image](https://github.com/srwi/EverythingToolbar/assets/63332824/eb263252-0b62-4c4a-ba8c-aa9cfafd7de7)

**Comment by MMMMMoris** [comment]
> Hello @MMMMMoris, which version of QuickLook are you using? I just tried it with the [latest version](https://github.com/QL-Win/QuickLook/releases/tag/3.7.3) and it seems to be fully functional. Does QuickLook work in Windows Explorer by pressing Space while having a file selected?

Yes, Quicklook works well  in Windows Explorer by pressing Space while having a file selected, as well as in Everything. It is just not functional in EvrythingToolBar. Mine is latest version downloaded from github,installed with msi package.
![image](https://github.com/srwi/EverythingToolbar/assets/63332824/eb263252-0b62-4c4a-ba8c-aa9cfafd7de7)

**Comment by MMMMMoris** [comment]
> Hello @MMMMMoris, which version of QuickLook are you using? I just tried it with the [latest version](https://github.com/QL-Win/QuickLook/releases/tag/3.7.3) and it seems to be fully functional. Does QuickLook work in Windows Explorer by pressing Space while having a file selected?

I works it out. Powertoys have taken the shortcutkey already.

![image](https://github.com/srwi/EverythingToolbar/assets/63332824/2474a11d-d018-471d-a7c5-87a1c5ddd8f8)

**Comment by srwi** [comment]
Cool, thanks for reporting back your findings!
