### ISSUE TITLE
Windows Copilot

### ISSUE THREAD

**Issue by neoOpus** [srwi/EverythingToolbar#430]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

Version 1.2.0.0

### Everything Version

Version 1.5.0.1352a (x64)

### Windows Version

25921.1000

### Steps to reproduce

Open Windows Copilot (sidebar)
Launch ET

### Expected Behavior

Should Open on the left bottom as usual or next to the start menu button

### Actual Behavior

it Opens on top right next to the Copilot sidebar

### Screenshots

![image](https://github.com/srwi/EverythingToolbar/assets/1388336/47a5554d-0e04-4e24-8ae7-eb1553f70221)

### Log output

2023-08-05 02:35:28.2722|INFO|Launcher|EverythingToolbar Launcher 1.2.0.0 started. OS: Microsoft Windows NT 10.0.25921.0|

**Comment by Horst12** [comment]
The Windows Copilot is currently only available in Insider versions
and also not in the EU.
Why should the toolbar run it at the current stage ?

**Comment by Mitia99** [comment]
> The Windows Copilot is currently only available in Insider versions and also not in the EU. Why should the toolbar run it at the current stage ?

Copilot(Preview) was released on Stable 2023-09 cumulative update. 
Not only EU use ET. I have it on stable build

**Comment by Mitia99** [comment]
![image](https://github.com/srwi/EverythingToolbar/assets/56766778/73d4176c-1c63-49b7-8c20-1874f43fb552)
