### ISSUE TITLE
Add "don't show again" checkbox to setup assistant

### ISSUE THREAD

**Issue by Yukai-Qian** [srwi/EverythingToolbar#433]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Hi, first of all this is a great app and I'd like to continue using it. However this has been a minor annoyance. At every startup, if I don't have a search icon pinned to the taskbar, the app will launch the setup assistant and ask me to do so. I eventually had to pin the icon just for the app to stop asking. 

I have configured a shortcut for EverythingToolbar and even if I pin an icon to the taskbar, I would not click it anyway. If I will need to move my hands to the keyboard to type the search query, then I might as well launch EverythingToolbar with a shortcut instead of using a mouse. 

### Proposed Solution

It would be nice if the setup assistant does not open just based on whether there is a pinned icon. 

### Alternatives Considered

I've considered just pinning the icon and calling it a day. But I'd still like to suggest not to ask the user again if they decide not to.

**Comment by srwi** [comment]
Hello @Yukai-Qian, this is happening because you are using EverythingToolbar in a quite unconventional way by launching it via the desktop shortcut rather than the taskbar icon.

I like your suggestion of adding a checkbox "don't show again" to the setup assistant!

**Comment by Yukai-Qian** [comment]
@srwi thank you for accepting my idea! I look forward to the update.

**Comment by srwi** [comment]
I added a popup dialog that asks if the user is sure they want to prematurely end the setup process. This will prevent the assistant from popping up again. It will still be accessible via the system tray icon.

This will be available in the next release.
