### ISSUE TITLE
[Issue] Open with... not working 

### ISSUE THREAD

**Issue by Mitia99** [srwi/EverythingToolbar#435]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.2.0

### Everything Version

1.5.0.1356a (x64)

### Windows Version

Windows 11 Pro 22H2

### Steps to reproduce

1. Install [Drawboard PDF](https://apps.microsoft.com/store/detail/drawboard-pdf/9WZDNCRFHWQT?hl=en-mg&gl=mg&rtc=1)
2. Add the program to `Rules...` for `Open with...`
Path is "C:\Program Files\WindowsApps\DRAWBOARD.DRAWBOARDPDF_6.47.2.0_x64__gqbn7fs4pywxm\Db.App.exe"

> I don't know if it will be the same path cause it was tricky to get it (There was no "Open file location" when searching Drawboard PDF in start menu)
> 
> Steps to get the program path
> I. Launch Drawboard PDF
> II. Open the Task Manager
> III. Go to details tab
> IV. Find Db.App.exe
> V. Right click then "Open file location"

3. Open Everything Toolbar
4. Search a PDF
5. Use `Open with...` and select Drawboard PDF

### Expected Behavior

PDF Opened in Drawboard PDF

### Actual Behavior

It only opens Drawboard PDF program not the file

### Log output

-

### Additional Information

An alternative fix will be to get Everything Toolbar context menu from Windows Explorer

**Comment by srwi** [comment]
Hello @Mitia99, you'll have to define the path with `%file%` at the end to pass the filename to the application:

    C:\Program Files\WindowsApps\DRAWBOARD.DRAWBOARDPDF_6.47.2.0_x64__gqbn7fs4pywxm\Db.App.exe %file%

**Comment by Mitia99** [comment]
@srwi Thanks for your reply. I already added the `%file%` at the end but as I said it only opens the app

**Comment by srwi** [comment]
In that case it really depends on the application. In general EverythingToolbar should be compatible with it as long as the command line usage is known and configured correctly.

Can you open a file in it using the same command in the command line?

**Comment by Mitia99** [comment]
Tried with **cmd** and I got the same issue

**Comment by srwi** [comment]
In that case it is an application-specific issue. Nothing I can do here.
