### ISSUE TITLE
Also display quick toggles icons in menu

### ISSUE THREAD

**Issue by Mitia99** [srwi/EverythingToolbar#439]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Quick Toggles in search bar is a convenient feature but it is not intuitive for new users to know buttons action.
I know that mouseover action helps but still.

### Proposed Solution

Also display quick toggles icons in menu
![image](https://github.com/srwi/EverythingToolbar/assets/56766778/8c7448e3-3dfd-4ea1-9b4e-c0c736c1608a)

**Comment by srwi** [comment]
I did some research with respect to UI design and it looks like checkboxes is the common design choice in this case. While I understand it makes sense to reuse the icons I don't think it would indicate the status clearly enough. 

Therefore I'd rather leave it as is.
