### ISSUE TITLE
1.3.0 bug when query includes space

### ISSUE THREAD

**Issue by scarletfrank** [srwi/EverythingToolbar#445]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.0.0

### Everything Version

V1.4.1.1024 (x64)

### Windows Version

Windows 10 Version 22H2

### Steps to reproduce

1. Open "Everything Bar" (Using Shortcuts)
2. Type one keyword
3. Try to "space" and type another keyword
4. can't input "space" as joint between two keyword

### Expected Behavior

I rollback to EverythingToolbar 1.2.0.0 and it can query sth like "xxx .pptx" 

### Actual Behavior

While using EverythingToolbar 1.3.0.0, it feels like "space" is forbidden to input

### Screenshots

I will add screenshots after work.

### Log output

 Sorry, I heavily depend on EvertythingToolbar, so I just rollback at once.
I will try the latest release after work and add the log file.

**Comment by redleafnew** [comment]
same issue, the space could not be entered.

**Comment by Horst12** [comment]
Not confirmed here.
I can use space at any place in the search string and the results are fine.
______________________________________________________
Windows 11 Home x64 Version 22H2 (OS Build 22621.2428)
Everything 1.5.0.1358a (x64), Everything Toolbar 1.3

**Comment by srwi** [comment]
It's probably related to how the settings are configured. I'll have a look later.

**Comment by Grooves1210** [comment]
Same here.  If QuickLook is running, I get the quicklook preview.
If I close QuickLook, then no spaces can be entered into the search box

**Comment by srwi** [comment]
It's a deskband issue (Windows 10). I'll try to get it fixed tomorrow or the day after. Sorry about that.

**Comment by jimkoutso2008** [comment]
I also have this issue.
Windows 11 23h2

**Comment by srwi** [comment]
> I also have this issue. Windows 11 23h2

I assume you are using the deskband with ExplorerPatcher or StartAllBack?

-----------

I already worked on the fix but it requires a little more effort than expected. I'm sure I will be able to release the fix by the end of this week. Sorry for the inconveniences.

**Comment by jimkoutso2008** [comment]
Yes I'm using StartAllBack.
Also no worries, take your time.

**Comment by redleafnew** [comment]
No StartAllbBack or ExplorerPatcher was used in my Win 10 machine.

**Comment by Erkhyan** [comment]
I’m using Win10 with ExplorerPatcher here, if it helps.

**Comment by srwi** [comment]
The fix was released in 1.3.1. Please let me know if there are any more problems related to this.
