### ISSUE TITLE
Everything window pops up after you click on a taskbar notification

### ISSUE THREAD

**Issue by Matzeeee** [srwi/EverythingToolbar#448]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.0.0

### Everything Version

1.4.1.1024

### Windows Version

Windows 10 Version 10.0.19045.3570

### Steps to reproduce

1. You got a taskbar notification
2. You klick away the taskbar notification
3. The taskbar notification closes ...
4. ... and the Everything Toolbar get focus and the Everything window pops up

### Expected Behavior

No Everything window pop up after clicking away a taskbar notification

### Actual Behavior

see Steps to reproduce

### Log output

2023-10-26 14:10:01.7108|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.0.0 started. OS: Microsoft Windows NT 10.0.19045.0
2023-10-26 14:10:10.6207|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1

**Comment by srwi** [comment]
Hi @Matzeeee, I would assume you are referring to the regular Windows 10 notifications?

Does this happen with each and every notification? Unfortunately I can not reproduce the problem. Are there any specific requirements to be met for it to happen?

Probably something is setting the keyboard focus to the EverythingToolbar search box placed in your taskbar.

Did you enable the option "Replace start menu search (experimental)"? Your issue might be related to #432.
