### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by Shamatix** [srwi/EverythingToolbar#451]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I see you can change shortcuts default being (Win+Alt+S)
I would like it to change the shortcut to Win or Win+S  but I dont seem to be able to do that.
Where is the config file with the shortcuts in so I can do it manually?

### Proposed Solution

Make me able to change the shortcut to Windows key or Win+S

### Alternatives Considered

Well where is the config file so I can do it manually :)?

**Comment by srwi** [comment]
It's currently not possible using the launcher icon. See #249
