### ISSUE TITLE
APPS key functionality

### ISSUE THREAD

**Issue by kmidm21iomiodaw** [srwi/EverythingToolbar#452]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.0.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 11

### Steps to reproduce

1. Open the EverythingToolbar search window
2. Press the arrow down key to change focus from the search bar to an item
3. Press the APPS key

### Expected Behavior

The context menu pertaining to the highlighted item opens.

### Actual Behavior

Nothing happens

### Log output

2023-11-01 21:59:42.9617|INFO|Launcher|EverythingToolbar Launcher 1.3.0.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2023-11-01 22:00:06.0666|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

**Comment by srwi** [comment]
Hi @kmidm21iomiodaw, this has already been requested in #101.

**Comment by srwi** [comment]
FYI: It was implemented in the 1.3.1 release.
