### ISSUE TITLE
"Applications" filter

### ISSUE THREAD

**Issue by Mitia99** [srwi/EverythingToolbar#453]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I would like to display applications(not executable) on search results.

### Proposed Solution

Have a **Application** filter.

### Additional Information

Maybe you can check [Flow Launcher code](https://github.com/Flow-Launcher/Flow.Launcher) which is also in C#

**Comment by srwi** [comment]
You can create custom filters for all applications in the start menu as described [here](https://github.com/srwi/EverythingToolbar/issues/443#issuecomment-1774072967).

Adding additional search results other than those supplied by Everything is out of scope for this project.
