### ISSUE TITLE
Can't type in numbers after updating to v1.3.1

### ISSUE THREAD

**Issue by ShahedFaisal** [srwi/EverythingToolbar#455]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.1

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 10 version 22H2

### Steps to reproduce

1. Update program version to 1.3.1
2. Open Everything toolbar
3. Start typing in numbers (using the number strip, not the numpad)
4. Numbers don't appear

### Expected Behavior

I should be able to type in numbers in search query.

### Actual Behavior

I'm unable to type in numbers in search query.

### Log output

2023-11-07 12:17:55.9054|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.1.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-11-07 12:45:35.5676|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-11-07 13:09:58.2646|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.1.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-11-07 13:10:08.7639|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

### Additional Information

I also attempted to input numbers using the On-Screen Keyboard, but that didn't work either. I can input numbers in other programs without any issues.

**Comment by Horst12** [comment]
**Bug Confirmed**
This needs a fast update, it makes version 1.3.1 almost useless

**Comment by srwi** [comment]
Sorry about that. Will be fixed soon.

> This needs a fast update, it makes version 1.3.1 almost useless

Quite harsh words for a free software. There is always the option to downgrade!

**Comment by Horst12** [comment]
> Sorry about that. Will be fixed soon.
> 
> > This needs a fast update, it makes version 1.3.1 almost useless
> 
> Quite harsh words for a free software. There is always the option to downgrade!
Don't take it so serious.
I'm still a fan of your tool.
Of course, I can downgrade, but I'll wait for your fix.
