### ISSUE TITLE
Run history

### ISSUE THREAD

**Issue by kamssiopeia** [srwi/EverythingToolbar#456]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Except for searching for something specific i often run same ~15 programs/games on my PC i would like to have option to display history of last X run programs

### Proposed Solution

Option to enable "run history" similar to how it works in original everything

### Alternatives Considered

Perhaps ability to stick / bookmark certain entries

**Comment by srwi** [comment]
You can achieve the behavior like in Everything's "run history" already with EverythingToolbar by sorting the results by run count. Additionally to that you could create a [custom filter that only searches shortcuts in the start menu](https://github.com/srwi/EverythingToolbar/issues/443#issuecomment-1774072967) to achieve the desired "most used programs".

I specifically don't want to add a feature to pin certain apps as that is outside the scope of this project and there are other better alternatives already out there (Flow Launcher, Wox, etc.)
