### ISSUE TITLE
add an option to hide trayicon 

### ISSUE THREAD

**Issue by akschy** [srwi/EverythingToolbar#463]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

The tray icon is not necessary, the settings in the tray icon can be merged into the options

### Proposed Solution

Provide an option to hide the tray icon

### Alternatives Considered

no

**Comment by Horst12** [comment]
You can already do this with the Windows tray options.
Just hide the icon.

**Comment by srwi** [comment]
#255
