### ISSUE TITLE
Customize The SortBy Menu

### ISSUE THREAD

**Issue by Raynbda** [srwi/EverythingToolbar#465]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I want to be able to only keep the ones that i can use and get rid of the ones that i have to enable from everything search

### Proposed Solution

add a button in the sortby drop down menu that says customize where youll be able to enable and disable 

### Alternatives Considered

i don't have any

**Comment by Horst12** [comment]
You can use any of the sort orders of Everything also from the Toolbar.
Why should there be any additional program effort for customization ?
Only because you personally don't need some of them ?

**Comment by srwi** [comment]
I also don't see a need for full customizability of the menu. I would like to close this issue in favor of #405 which would already cut the amount of menu entries almost in half.
