### ISSUE TITLE
Sort by Date Accessed Ascending/Descending not working.

### ISSUE THREAD

**Issue by ZechyWasNotAvailable** [srwi/EverythingToolbar#467]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.2.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 11 Home 22H2 Build: 22621.2715

### Steps to reproduce

1. Open EverythingToolbar
2. Click 3 dots
3. Hover over/click on sort by
4. Change sort type to Date accessed ascending or descending
5. ![image](https://github.com/srwi/EverythingToolbar/assets/104027572/0500ab40-8beb-42ea-9482-b836f30a1c64)
6. Cry

### Expected Behavior

To change the sort type to be by date accessed ascending or descending. Just like the Everything application does.

### Actual Behavior

Throws up error
![image](https://github.com/srwi/EverythingToolbar/assets/104027572/0500ab40-8beb-42ea-9482-b836f30a1c64)
Even though my sort by date accessed works on Everything.

### Log output

2023-11-28 18:38:45.3345|INFO|Launcher|EverythingToolbar Launcher 1.3.2.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2023-11-28 18:42:09.2633|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

**Comment by Horst12** [comment]
And why don't you set in Everything what the error message says ?
Enable "Fast date modified sort" under Indexes.
The sort function of the Toolbar works fine
______________________________________________________
Windows 11 Home x64 Version 23H2 (OS Build 22631.2715)
Everything 1.5.0.1360a (x64), Everything Toolbar 1.3.2

**Comment by ZechyWasNotAvailable** [comment]
![image](https://github.com/srwi/EverythingToolbar/assets/104027572/f54b1607-68f5-436e-918f-2591245ffc04)
These are my Everything options under Indexes.

**Comment by ZechyWasNotAvailable** [comment]
https://github.com/srwi/EverythingToolbar/assets/104027572/93a2284d-b09b-411c-99b0-5210743264d3

**Comment by srwi** [comment]
As @Horst12 mentioned, it shoud work once you enable these two options:

![image](https://github.com/srwi/EverythingToolbar/assets/17520641/7f290d54-9665-4ae7-a576-adced273feaf)

Side note: Are you sure it is actually sorted by date accessed in Everything? Looks like it is still sorting by name to me.
