### ISSUE TITLE
"regex:" Filter doesn't work with pipes.

### ISSUE THREAD

**Issue by Alfamari** [srwi/EverythingToolbar#468]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.2.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 10 Home Version: 22H2

### Steps to reproduce

type regex:(.\*|.\*) or anything in parentheses separated by a pipe

### Expected Behavior

Returns corresponding results via the regex filter that's separated by a pipe.
if regex:(.\*|.\*) is given, it should return all results, the same as typing nothing at all.

### Actual Behavior

No results found.

### Screenshots

![Everything_xJbM7EkDvA](https://github.com/srwi/EverythingToolbar/assets/132071593/203ce2ea-c056-4713-a55c-422c4c85b8a1)
![Everything_AiqmKwyzrj (edit)](https://github.com/srwi/EverythingToolbar/assets/132071593/cbe41613-d2dd-463b-b771-3091a3882ec9)
![image](https://github.com/srwi/EverythingToolbar/assets/132071593/2b2f19f8-7069-4566-b379-43383da5aa77)
![Everything_pZmOKteGUn (edit)](https://github.com/srwi/EverythingToolbar/assets/132071593/a89ea1f3-319c-4993-8e01-ae07fad077a1)

### Log output

2023-11-29 14:06:08.7843|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-11-29 17:22:37.6479|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

### Additional Information

If enabling regular expressions via the menu or hotkey: ctrl+r, it works as expected.
Problem and workaround behave identically in both base program and in deskband.

**Comment by srwi** [comment]
Hi @Alfamari, I don't really understand how this relates to EverythingToolbar. It seems like EverythingToolbar does the exact same thing as Everything, which is the way it is intended. This seems like a bug in Everything to me and should be reported [here](https://voidtools.com/forum/viewforum.php?f=6&sid=a82ae25d2cbd6f023e37a1d02216f6e5).

**Comment by Alfamari** [comment]
Ah, it seems I got confused with the main program and the toolbar. I agree I should post it there, apologies.
