### ISSUE TITLE
EveryThing Toolbar not remaining in collapsed position when signing out/restarting PC.

### ISSUE THREAD

**Issue by Joeys3ph** [srwi/EverythingToolbar#473]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.2

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 10 Home (22H2)

### Steps to reproduce

1. Reposition Everything Toolbar to the left side of the screen/collapse it or minimize it as much as possible.
![yvlcMfcx1i](https://github.com/srwi/EverythingToolbar/assets/107140860/3182e166-9efd-4b9d-b2ae-84c9715cef7d)

2. Sign out of Windows or restart PC.

3. Everything Toolbar is now fully extended and intrusive. 
![iDa8BBELcM](https://github.com/srwi/EverythingToolbar/assets/107140860/8e0d8004-84db-4e32-9737-f8c0f9f6c090)

### Expected Behavior

Everything Toolbar stays in the same position (Left side of taskbar) and remains collapsed.

### Actual Behavior

Everything Toolbar uncollapses itself and is no longer just a search icon. 'Search with Everything' pops up and it takes up almost my entire taskbar.

### Log output

2023-12-14 00:20:02.1553|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-12-14 00:21:01.5445|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-12-14 00:26:22.2605|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-12-14 00:37:23.5513|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-12-14 00:38:23.5814|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

### Additional Information

I have PersistentWindows installed. I am not sure if that might be interfering with it. Will do some troubleshooting myself on that.

**Comment by srwi** [comment]
I am not sure whether that's a problem of EverythingToolbar or due to external factors. So far, EverythingToolbar doesn't control it's size on its own. I know that Windows sometimes takes a while to "remember" the last toolbar size/position. Maybe it helps if you resize it and give it a few minutes/hours to settle so that Windows correctly restores the last size on restart/login.

As you already mentioned, please also try disabling external tools to see if that could have an effect.
