### ISSUE TITLE
Windows 10 search menu for windows 11

### ISSUE THREAD

**Issue by Nicolasdavinci08** [srwi/EverythingToolbar#474]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Hello, I am writing to you today for a possible feature that you guys can add, after 0.8.0-beta1, windows 11 support was added, but I prefer the style of the Windows 10 search menu, although you CAN edit the files to enable the windows 10 theme, the start menu is floating, so it doesn't look exactly looks like windows 10.

![Windows  10  search after version 0 8 0 beta 2](https://github.com/srwi/EverythingToolbar/assets/113314172/0f793a1c-db73-47b7-b943-7a8dbb52a45e)
![Windows 10 search before version 0 8 0 beta 2](https://github.com/srwi/EverythingToolbar/assets/113314172/d8da2b04-6c4a-4ecc-991c-fc627ff18a37)

### Proposed Solution

If that's not a good solution, why don't you try making separate themes, or make a theme system? thanks!

### Alternatives Considered

Can you add a separate windows 11 and 10 theme that makes it look like said search boxes? thanks!

**Comment by Nicolasdavinci08** [comment]
im sorry idk how github works

**Comment by srwi** [comment]
I added a flag that allows you to override the OS build number to that of Windows 10. The option can be set in the user.config file for EverythingToolbar (unfortunately the config location currently varies a bit, see https://github.com/srwi/EverythingToolbar/issues/313):

```xml
<setting name="OSBuildNumberOverride" serializeAs="String">
    <value>14393</value>
</setting>
```

This will be available in the next release.

**Comment by Nicolasdavinci08** [comment]
also, I'm sorry if this is a bit needy, but can the toolbar also have a task view button next to it so that it looks really close to windows 10? Thanks!

**Comment by kekkodance** [comment]
sorry but, this isn't working out for me, how can one achieve this?

**Comment by srwi** [comment]
> sorry but, this isn't working out for me, how can one achieve this?

The settings file is now located at `%APPDATA%\EverythingToolbar\settings.ini` so you need to set the value in there. After restarting EverythingToolbar it should work as expected. 

```ini
OsBuildNumberOverride=14393
```
