### ISSUE TITLE
Update Main Instructions for v1.5a Setting

### ISSUE THREAD

**Issue by IanJSaul** [srwi/EverythingToolbar#477]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Being completely new to both Everything search and Everything Toolbar - I was left scratching my head how to link them.

"Note: For Everything 1.5a the instance name 1.5a must be set in the EverythingToolbar settings."

### Proposed Solution

A quick sub-note (or perhaps a screenshot) of the "Set instance name..." config field.

![image](https://github.com/srwi/EverythingToolbar/assets/50129447/eb0927da-02b7-46c4-8532-755cbbce8c4f)

### Alternatives Considered

I searched around but was unable to discover the answer. I stumbled across the setting after attempting to reinstall.

### Additional Information

Thanks for making an amazing piece of software!

**Comment by srwi** [comment]
Thank you for the suggestion. I added your screenshot to the instructions. Hopefully it will help the next person!
