### ISSUE TITLE
Open EverythingToolbar when typing text while the start menu is opened

### ISSUE THREAD

**Issue by Carbone13** [srwi/EverythingToolbar#478]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

I generally research things by opening the start menu with the windows key and then typing my search query. Doing this use the old windows search tools instead of Everything Toolbar

### Proposed Solution

Use EverythingToolbar instead of the windows search

### Alternatives Considered

/

**Comment by Horst12** [comment]
What is the benefit not using the Toolbar ?
It's an icon in the taskbar, and you only need one press to start entering your search

**Comment by Carbone13** [comment]
Opening the search prompt with the windows key is faster as... it's a key press instead of having to move your mouse to the precise, small, search icon.
Also it's just muscular memory, but anyway it's just faster

**Comment by srwi** [comment]
This is already implemented with the experimental "Replace Start menu search" option. But it has it's issues. See #471.
