### ISSUE TITLE
Lower minimum toolbar size (Win 10)

### ISSUE THREAD

**Issue by SnazzLAN** [srwi/EverythingToolbar#479]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Currently the minimum-size Win 10 toolbar has a lot of padding (24px) around the search icon, taking up precious taskbar real estate.

![TakeUpEverythingBar](https://github.com/srwi/EverythingToolbar/assets/82859037/84cff2f1-a6c3-44b1-9c0d-571163026077)

### Proposed Solution

It would be great if we could shrink the Windows 10 toolbar further, I seem to remember it being shorter (on a vertical/side taskbar) in a previous version.

### Alternatives Considered

Ideally, we would be able to reduce the toolbar dimensions to the point the icon/button is not even visible, while still being able to use the shortcut key to open the search window. 
I know it's called "Everything**Toolbar**", but I use it for the superior Everything interface that the toolbar/shortcut opens.

**Comment by srwi** [comment]
Hi, I reduced the minimum size slightly with the 1.5.0 release.

Probably more interesting for you would be to use the launcher variant of EverythingToolbar instead. For that you can disable the deskband and run the "EverythingToolbar.Launcher.exe". Once the setup assistant opens, close it without following the steps.

After that you can open EverythingToolbar using the keyboard shortcut and no deskband or taskbar icon will be necessary.
