### ISSUE TITLE
Unexpected crash/exception all of a sudden

### ISSUE THREAD

**Issue by bel57** [srwi/EverythingToolbar#488]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.2.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 11 23H2 (22631.3296)

### Steps to reproduce

I'm not sure, usually the program is very stable. It unexpectedly crashed while I doing random stuff (browsing web)

### Expected Behavior

No crash?

### Actual Behavior

Crashed and can't be relaunched manually. I guess it will be working as normal after restarting the system. Restarting explorer.exe won't fix it. At least it's not returning constant errors, crashed and done. Thanks for looking into it

### Log output

2024-03-28 05:40:54.8815|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-03-28 05:40:55.2594|ERROR|CSDeskBand.Deskband|Unhandled exception|System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'EverythingToolbar.Behaviors.ThemeAwareness' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.Management.ManagementException: Violation de quota 
   à System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   à System.Management.ManagementEventWatcher.Start()
   à EverythingToolbar.Helpers.RegistryWatcher..ctor(RegistryEntry target) dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Helpers\RegistryWatcher.cs:ligne 45
   à EverythingToolbar.Behaviors.ThemeAwareness..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Behaviors\ThemeAwareness.cs:ligne 60
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à EverythingToolbar.ToolbarControl..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\ToolbarControl.xaml.cs:ligne 19
   à CSDeskBand.Deskband..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\Deskband.cs:ligne 24
2024-03-28 05:48:15.3281|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-03-28 05:48:15.4342|ERROR|CSDeskBand.Deskband|Unhandled exception|System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'EverythingToolbar.Controls.SearchButton' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'EverythingToolbar.SearchWindow'. ---> System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'EverythingToolbar.Behaviors.ThemeAwareness' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.Management.ManagementException: Violation de quota 
   à System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   à System.Management.ManagementEventWatcher.Start()
   à EverythingToolbar.Helpers.RegistryWatcher..ctor(RegistryEntry target) dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Helpers\RegistryWatcher.cs:ligne 45
   à EverythingToolbar.Behaviors.ThemeAwareness..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Behaviors\ThemeAwareness.cs:ligne 60
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à EverythingToolbar.SearchWindow..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\SearchWindow.xaml.cs:ligne 21
   à EverythingToolbar.SearchWindow..cctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\SearchWindow.xaml.cs:ligne 13
   --- Fin de la trace de la pile d'exception interne ---
   à EverythingToolbar.Controls.SearchButton..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\SearchButton.xaml.cs:ligne 16
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à EverythingToolbar.ToolbarControl..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\ToolbarControl.xaml.cs:ligne 19
   à CSDeskBand.Deskband..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\Deskband.cs:ligne 24
2024-03-28 05:51:27.9321|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-03-28 05:51:27.9815|ERROR|CSDeskBand.Deskband|Unhandled exception|System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'EverythingToolbar.Controls.SearchButton' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'EverythingToolbar.SearchWindow'. ---> System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'EverythingToolbar.Behaviors.ThemeAwareness' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.Management.ManagementException: Violation de quota 
   à System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   à System.Management.ManagementEventWatcher.Start()
   à EverythingToolbar.Helpers.RegistryWatcher..ctor(RegistryEntry target) dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Helpers\RegistryWatcher.cs:ligne 45
   à EverythingToolbar.Behaviors.ThemeAwareness..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Behaviors\ThemeAwareness.cs:ligne 60
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à EverythingToolbar.SearchWindow..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\SearchWindow.xaml.cs:ligne 21
   à EverythingToolbar.SearchWindow..cctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\SearchWindow.xaml.cs:ligne 13
   --- Fin de la trace de la pile d'exception interne ---
   à EverythingToolbar.Controls.SearchButton..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\SearchButton.xaml.cs:ligne 16
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à EverythingToolbar.ToolbarControl..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\ToolbarControl.xaml.cs:ligne 19
   à CSDeskBand.Deskband..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\Deskband.cs:ligne 24
2024-03-28 05:51:44.7027|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.2.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-03-28 05:51:44.9773|ERROR|CSDeskBand.Deskband|Unhandled exception|System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'EverythingToolbar.Behaviors.ThemeAwareness' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.Management.ManagementException: Violation de quota 
   à System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   à System.Management.ManagementEventWatcher.Start()
   à EverythingToolbar.Helpers.RegistryWatcher..ctor(RegistryEntry target) dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Helpers\RegistryWatcher.cs:ligne 45
   à EverythingToolbar.Behaviors.ThemeAwareness..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Behaviors\ThemeAwareness.cs:ligne 60
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   à EverythingToolbar.ToolbarControl..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\ToolbarControl.xaml.cs:ligne 19
   à CSDeskBand.Deskband..ctor() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\Deskband.cs:ligne 24
2024-03-28 05:52:55.4157|INFO|Launcher|EverythingToolbar Launcher 1.3.2.0 started. OS: Microsoft Windows NT 10.0.22631.0|

### Additional Information

System tweaks:
-StartAllBack
-ExplorerBlurMica
-PowerToys

**Comment by srwi** [comment]
Hi @bel57, possibly there are other applications using up WMI resources which causes the quota violation. I don't think there is a good solution other than catching the error and disabling the automatic theme switching whenever the limit is reached. But before I implement that it would be good to know whether the problem is resolved after rebooting the machine (I would think so).

**Comment by srwi** [comment]
I released a fix for it. We can reopen the issue if the problem persists.

**Comment by bel57** [comment]
Sorry forgot to reply; I have an important task running that I can't pause right now so it's preventing me to restart my workstation. However, installed the update, launched the program and reenabled the taskbar widget: so far so good, no error anymore. Thanks for the quick fix, will reach back if any issue arises. 🙂
