### ISSUE TITLE
The  height of the toolbar's search result list cannot be fixed  

### ISSUE THREAD

**Issue by cangzhouyuhe** [srwi/EverythingToolbar#491]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

 V1.4.1.1024 (x64)

### Everything Version

1.3.3.0

### Windows Version

Windows 10 version 22H2

### Steps to reproduce

After enabling "desktop mode to automatically hide the taskbar" in Win10, the height of the search results list in the toolbar will continue to increase. 
I think most users will turn on "desktop mode to automatically hide the taskbar", after all, this will make Windows more beautiful. Can you solve the problem of height not being fixed?

### Expected Behavior

After enabling "desktop mode to automatically hide the taskbar" in Win10, the height of the search results list in the toolbar won't continue to increase. 

### Actual Behavior

After enabling "desktop mode to automatically hide the taskbar" in Win10, the height of the search results list in the toolbar will continue to increase. 

### Screenshots

![截图_20240405174420](https://github.com/srwi/EverythingToolbar/assets/50189901/6f0cf22c-b8cd-4620-9501-d8569fc58d00)

### Log output

2024-04-05 17:07:45.6068|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.3.3.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2024-04-05 17:08:00.7609|INFO|Launcher|EverythingToolbar Launcher 1.3.3.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2024-04-05 17:08:02.3255|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

**Comment by srwi** [comment]
#434
