### ISSUE TITLE
MSI Installer: ProgramFiles64Folder is not used, even if this was intended

### ISSUE THREAD

**Issue by tinojohn** [srwi/EverythingToolbar#496]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.3.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 11 23H2

### Steps to reproduce

Even if the directory ProgramFiles64Folder Property is used within the MSI for the installation, the MSI cannot be installed to C:\Program Files, but only to c:\Program Files (x86), because the platform is set to “Intel” instead of “x64” in the Summary Information Stream.
This means that the MSI can be installed on x86 systems, but never in the intended installation path on x64 systems.

Attention: If this is changed, the MSI can no longer be installed on x86 systems

### Expected Behavior

EverythingToolbar installed to C:\Program Files\EverythingToolbar instead of C:\Program Files (x86)\EverythingToolbar on x64 systems

### Actual Behavior

EverythingToolbar installed to C:\Program Files (x86)\EverythingToolbar instead of C:\Program Files\EverythingToolbar on x64 systems

### Screenshots

![2024-04-26_15h00_44](https://github.com/srwi/EverythingToolbar/assets/40440866/e7d3a9fc-4b5e-466d-aa44-35b8ca013c85)

### Log output

-

**Comment by srwi** [comment]
Hi @tinojohn, I dropped the x86 build target (AnyCPU) since it wasn't supported anyway. In the next release the msi will install into `C:\Program Files` as expected. Thanks for bringing it to my attention again!

**Comment by hangukhiphop** [comment]
While we're at it, could location be optional, please?

**Comment by hangukhiphop** [comment]
Oh, you know what? Turns out install directory _is_ optional however _**not**_ when installed via Winget. Weird! Never mind that, then.
