### ISSUE TITLE
一如既往的超难用。你就将Everything原版美化到托盘图标都比现在好得多。

### ISSUE THREAD

**Issue by ednykissyou** [srwi/EverythingToolbar#506]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.3

### Everything Version

1.5a

### Windows Version

win11

### Steps to reproduce

几年前我就用过，今天突然又想起，又用了下，虽然刚开始还是有点卡，但改进了不少。
另外这种小程序就整绿色免安装的就好。
还要去安装不够有点麻烦了，现在就是一托盘图标。
不必想太复杂

### Expected Behavior

这github事真多，要填这么多

### Actual Behavior

这github事真多，要填这么多

### Screenshots

这github事真多，要填这么多

### Log output

这github事真多，要填这么多

### Additional Information

这github事真多，要填这么多

**Comment by cangzhouyuhe** [comment]
你这样说不太友善吧？恐怕只能改发泄情绪。哪里不好用、有什么问题，为什么不逐一反给作者看呢？之前向作者反馈过一些问题，作者还是很乐意听取不同意见的。

**Comment by zuilintan** [comment]
致后来者, 
Title是情绪输出, 
Content有效内容为"**就整绿色免安装的就好**", 

不要浪费时间进行嘲讽和劝解的回复, 不值, 
回想一下你来此的目的, Do it

**Comment by china-live** [comment]
话虽然难听，但却是实话。
1. 这个EverythingToolbar是意义是什么，扩展系统原生搜索框吗？ 在有Everything的情况下，都是直接禁用windows自带的搜索的，难用还是其次，有乱七八糟的资讯和广告完全不能忍，PC电脑是生产力工具，新闻、资讯什么的太影响效率。
2. 他说的没错，这种小程序就整绿色免安装就行了，还要安装确实麻烦了（还不支持仅用户安装）。
3. Everything原版的图标确实有点不符合win10和win11，能美化一下图标，或直接将搜索栏集成到任务栏就完美了。

**Comment by srwi** [comment]
From what I understand via Google Translate, you're requesting a portable installation. While it wasn't practical for the deskband alone (due to needing admin rights), the new launcher variant makes this feasible. I'll reopen the previous issue for this: #156.
