### ISSUE TITLE
Request to add customizable theme color feature

### ISSUE THREAD

**Issue by cangzhouyuhe** [srwi/EverythingToolbar#508]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

in a subsequent version update, the theme color setting was changed to "follow system settings," which may have been intended to simplify the user settings process and maintain consistency across the system. Unfortunately, this change has caused some issues for Windows users when setting the color of their computer's taskbar. Specifically, the taskbar only allows color changes when the system is in dark mode, which results in the taskbar matching the black toolbar when using any other default color setting.

### Proposed Solution

 I would like to suggest restoring the customizable theme color feature, allowing users to choose between a dark or light theme as per their preference. This change would enhance user experience and cater to a wider range of user preferences.

### Alternatives Considered

Just like the previous versions, users had the option to choose between a dark theme or a light theme, which provided a great deal of personalization.

**Comment by tanghululalala** [comment]
I want that too.

**Comment by srwi** [comment]
Hi, you got it right on why I removed the option to choose a theme but I added a poweruser option in the `%APPDATA%\EverythingToolbar\settings.ini` that allows you to set `ThemeOverride=dark` or `ThemeOverride=light` again. It will be available in the next release.
