### ISSUE TITLE
winget installation issues

### ISSUE THREAD

**Issue by EdiTurn** [srwi/EverythingToolbar#512]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.4

### Everything Version

1.5a

### Windows Version

Windows 11 24H2

### Steps to reproduce

`winget install everythingtoolbar`

### Actual Behavior

I got three issues during installation with winget: 
1. winget told me there are multiple packages

> EverythingToolbar   stnkl.EverythingToolbar
    EverythingToolbar   stnkl.EverythingToolbar.Beta

2. I have Everything 1.5a installed, but winget still install Everything 1.4 to my computer, 
3. The Beta's version is still 0.8.0-beta2.

**Comment by EdiTurn** [comment]
> `winget install stnkl.EverythingToolbar`

Yes, and it leads to the second issue above.

**Comment by KoBruh** [comment]
winget instaall --id stnkl.EverythingToolbar is the fix to this issue

**Comment by EdiTurn** [comment]
> `winget install --id stnkl.EverythingToolbar` is the fix to this issue

I know how to install a specific package. However, either the README need modification, or the deprecated Beta version should be removed.

**Comment by srwi** [comment]
I updated the readme and changed the winget release workflow to update both the stable and beta package. The beta package will include both stable and prereleases while the regular package will include only stable releases.
