### ISSUE TITLE
搜索结果是空的

### ISSUE THREAD

**Issue by klxq520** [srwi/EverythingToolbar#514]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

搜索结果什么都没有，用独立的everything则没有问题

### Proposed Solution

刚安装完就这样，是我安排有问题吗？

### Alternatives Considered

不知道是个例还怎样，望改进。

### Additional Information

![000](https://github.com/srwi/EverythingToolbar/assets/45682501/e6a39045-fbb9-453f-b5a5-6b486a0d4f09)

**Comment by SeekFortheSun** [comment]
看了readme么？不支持lite版本的everything，应该是这个导致的没正确调用everything

**Comment by jkobtr** [comment]
我的也是这个问题。。everything版本是Version 1.5.0.1383a (x64)

**Comment by srwi** [comment]
Most likely the problem is one of the following:
- [Everything](https://www.voidtools.com) is not running in the background
- You are using Everything Lite, which is not supported by EverythingToolbar
- You are using Everything 1.5a for which you'll need to set the instance name to `1.5a` which is explained in the [readme](https://github.com/srwi/EverythingToolbar?tab=readme-ov-file#installation).

**Comment by klxq520** [comment]
> Most likely the problem is one of the following:问题很可能是以下问题之一：
> 
> * [Everything](https://www.voidtools.com) is not running in the background一切都没有在后台运行
> * You are using Everything Lite, which is not supported by EverythingToolbar您正在使用 Everything Lite，它不受 EverythingToolbar 支持
> * You are using Everything 1.5a for which you'll need to set the instance name to `1.5a` which is explained in the [readme](https://github.com/srwi/EverythingToolbar?tab=readme-ov-file#installation).您正在使用 Everything 1.5a，您需要为其设置自述文件中解释的实例名称 `1.5a` 。

关于第3点可以说一下具体怎么操作吗？

**Comment by srwi** [comment]
> 关于第3点可以说一下具体怎么操作吗？

This only applies if you installed Everything 1.5a:

- Click the three dot menu to bring up EverythingToolbar options
- Navigate to "Settings"
- Click "Set instance name"
- Enter `1.5a` and click OK

![c8e6f9ad-9f33-4ad9-92c1-788b5f7f438a](https://github.com/srwi/EverythingToolbar/assets/17520641/32bec4eb-dc8c-4b17-a258-ce80a31ab294)

After that EverythingToolbar should give you search results. Remember that Everything 1.5a has to be running in the background for that.
