### ISSUE TITLE
Replace Start menu search-Lose focus after typing a few characters

### ISSUE THREAD

**Issue by ExcuseLme** [srwi/EverythingToolbar#515]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.4.0

### Everything Version

V1.4.1.1024 (x64)

### Windows Version

Windows 11 23H2 22631.3810

### Steps to reproduce

1. Turn on the setting "Replace Start menu search"
2. Hit the "win" key
3. Input some characters
4. Trigger EverythingToolbar, jump to EverythingToolbar's ui
5. Only the first few characters entered are substituted into the EverythingToolbar input box, then lost focus from EverythingToolbar's input box

### Expected Behavior

after trigger EverythingToolbar, jump to EverythingToolbar's ui, the focus always in EverythingToolbar's input box

### Actual Behavior

lost focus from EverythingToolbar's input box

### Screenshots

![image](https://github.com/srwi/EverythingToolbar/assets/43724060/459b7fce-3ef1-4ad5-b688-a9ee6f60ed30)

### Log output

2024-07-04 17:04:39.9981|INFO|Launcher|EverythingToolbar Launcher 1.3.4.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-07-04 17:05:58.6453|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

**Comment by srwi** [comment]
Hi @ExcuseLme, thank you for the bug report. This is a known issue (#341) and tracked in the meta issue #471. Therefore I'll close this one as a duplicate.
