### ISSUE TITLE
Wrong selection of cvs file, can't you select it again?

### ISSUE THREAD

**Issue by jp1017** [srwi/EverythingToolbar#516]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.4.0

### Everything Version

1.4.1.1024 x64

### Windows Version

win11

### Steps to reproduce

选择 flters.cvs时选择了ini文件，现在不能弹出选择框，不能重新选择。卸载后，重启，也不行，尴尬了。win11还没有安卓那种清空数据，软件初始化的操作。

### Expected Behavior

每次选择cvs弹出选择框。

### Actual Behavior

每次选择cvs弹出选择框。每次选择cvs弹出选择框。

### Log output

每次选择cvs弹出选择框。

**Comment by srwi** [comment]
The easiest way should be to just remove your settings completely. For that you can close EverythingToolbar from the system tray and remove the folder `%LOCALAPPDATA%\EverythingToolbar`.

Afterwards you will be prompted again to select the filters.csv file.

**Comment by jp1017** [comment]
3ks
