### ISSUE TITLE
快捷键无法清空/删除

### ISSUE THREAD

**Issue by yahuudang** [srwi/EverythingToolbar#519]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

已经快捷键无法删除，按DELETE，就会把DELETE设置为快捷键

### Proposed Solution

按DELETE时，清空快捷键

### Alternatives Considered

无

**Comment by srwi** [comment]
Hi @yahuudang, the shortcut can be deleted by pressing <kbd>Esc</kbd>.
