### ISSUE TITLE
Loss of focus

### ISSUE THREAD

**Issue by HMwancheng** [srwi/EverythingToolbar#520]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.4

### Everything Version

1.4.1.1024

### Windows Version

Windows 11 23H2

### Steps to reproduce

press win key to start
![image](https://github.com/user-attachments/assets/78891e81-5a14-4304-9f54-ac2d01ec4195)
press any key to skip to search
(now auto change toEverythingToolbar)
![image](https://github.com/user-attachments/assets/1f897aea-f406-424f-a7fd-7097aae31807)
now, EverythingToolbar Loss of focus, can't input except press the search window again

### Expected Behavior

focus

### Actual Behavior

focus

### Log output

[EverythingToolbar.log](https://github.com/user-attachments/files/16321156/EverythingToolbar.log)

**Comment by liamwhan** [comment]
Seeing this as well, just discovered this extension and this makes it a non-starter unfortunately

**Comment by srwi** [comment]
Yes, the start menu replacement was written for Windows 10 as an experimental feature. It needs a complete rewrite at some point.
