### ISSUE TITLE
Reduce precision of file size

### ISSUE THREAD

**Issue by user1823** [srwi/EverythingToolbar#527]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

The file size is reported too precisely in the search results in the Normal (detailed) view.

![image](https://github.com/user-attachments/assets/001a79b0-fa4e-4941-a298-e26cf29d03f1)

### Proposed Solution

I think that a max. of 3 significant digits would be enough. So,

- 225.442 MB would become 225 MB
- 32.784 MB would become 32.8 MB
- 1246.563 MB would become 1.25 GB

### Alternatives Considered

-

### Additional Information

I think that the Windows File Explorer also limits the number of significant digits to 3 in the bottom bar.

**Comment by srwi** [comment]
Very good point. I implemented it according to your suggestion!
