### ISSUE TITLE
EverythingToolbar 1.4.0 & 1.4.1 publish to Winget failed

### ISSUE THREAD

**Issue by Gerome100** [srwi/EverythingToolbar#530]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.4.0

### Everything Version

1.4.1.1026 (x64)

### Windows Version

Windows 11 Pro version 23H2

### Steps to reproduce

I am not able to reproduce this.

### Expected Behavior

Publish EverythingToolbar version 1.4.0 & 1.4.1 to Winget repository successfully.

### Actual Behavior

Publishing EverythingToolbar version 1.4.0 & 1.4.1 to Winget repository fails.

### Log output

```
Run $gitToken = "***"
  $gitToken = "***"
  $github = Invoke-RestMethod -uri "https://api.github.com/repos/srwi/EverythingToolbar/releases"
  $targetRelease = $github | Where-Object { $_.prerelease -eq $false } | Select -First 1
  $installerUrl = $targetRelease | Select -ExpandProperty assets -First 1 | Where-Object -Property name -match "EverythingToolbar.*msi" | Select -ExpandProperty browser_download_url
  iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
  .\wingetcreate.exe update stnkl.EverythingToolbar -s -v $targetRelease.tag_name -u $installerUrl -t $gitToken
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
Telemetry Settings
------------------
The Windows Package Manager Manifest Creator collects usage data in order to improve your experience.
The data is anonymous and collected only by Microsoft.
By default, telemetry is enabled but can be disabled by running `wingetcreate settings` and editing your settings file.

Retrieving latest manifest for stnkl.EverythingToolbar
Base manifest contains DisplayVersion that has not been updated. Use --display-version CLI arg or provide the version in the installer URL.
Downloading and parsing: https://github.com/srwi/EverythingToolbar/releases/download/1.[4](https://github.com/srwi/EverythingToolbar/actions/runs/10760551439/job/29838652652#step:2:4).1/EverythingToolbar-1.4.1.msi...
Each new installer URL must have a single match to an existing installer based on architecture, installer type and scope. The following installers failed to match an existing installer:
Multiple matches found for X64 Wix installer detected from the url: https://github.com/srwi/EverythingToolbar/releases/download/1.4.1/EverythingToolbar-1.4.1.msi
Try using the architecture and/or scope overrides to uniquely match new URLs to existing installer nodes in the manifest.
Error: Process completed with exit code 1.
```

### Additional Information

The logfile content is not from %TEMP%\EverythingToolbar.log it is from the workflow "Publish release to WinGet" 

https://github.com/srwi/EverythingToolbar/actions/runs/10760551439/job/29838652652#logs

I am sorry if I did something wrong, I absolutely have no idea how to work with GitHub properly but wanted to address the issue.

**Comment by srwi** [comment]
Hi, this is due to some changes to the installer. I am aware of the issue and just need to find some time to look into it. 😊

**Comment by Gerome100** [comment]
Alright, thanks for the quick reply!

**Comment by srwi** [comment]
I triggered the update manually. It should work again from now on. The latest release will be available via winget once it's approved.

**Comment by Gerome100** [comment]
Awesome, it is already available! Thank you so much!
