### ISSUE TITLE
Can't open folders that have a comma in name

### ISSUE THREAD

**Issue by Bedz01** [srwi/EverythingToolbar#531]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.4.1.0

### Everything Version

1.4.1.1023 (x64)

### Windows Version

Windows 11 Pro 10.0.22631

### Steps to reproduce

1. Make a folder that has a comma in it's name. For example "test, 1".
2. Find it in EverythingToolbar
3. Try open it.

### Expected Behavior

Opens the correct folder.

### Actual Behavior

Opens "My Documents" instead. 
However, if you have two folders named like so:

> test
> test, 1

When you try open "test, 1" it opens "test" instead.

### Screenshots

![image](https://github.com/user-attachments/assets/1f6bc01a-b01d-4986-ac14-7af1340c5054)

### Log output

2024-09-12 14:27:48.8119|INFO|Launcher|EverythingToolbar 1.4.1.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-09-12 14:27:51.3116|INFO|EverythingToolbar.EverythingSearch|Setting Everything instance name: lmc|
2024-09-12 14:27:51.3429|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

**Comment by Horst12** [comment]
**Not confirmed, no such problem here.**
______________________________________________________
Windows 11 Home x64 Version 23H2 (OS Build 22631.4169)
Everything 1.5.0.1383a (x64), Everything Toolbar 1.4.1

**Comment by srwi** [comment]
Actually I was able to reproduce and fix the problem. The fix will be included in the next release. Thanks for reporting the problem!
