### ISSUE TITLE
Crash Second monitor, vertical taskbar

### ISSUE THREAD

**Issue by kokanas** [srwi/EverythingToolbar#532]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.4.1

### Everything Version

does not matter

### Windows Version

Win11 22631.4169

### Steps to reproduce

Im using Explorer Patcher for Win10 taskbar
Connect second monitor
place taskabar vertically either left or right side on sencond monitor (not main)
try to use toolbar
crash

### Expected Behavior

no crash

### Actual Behavior

program crashes

### Screenshots

![image](https://github.com/user-attachments/assets/2329a1e9-1cb2-4a0f-950e-52f1a94a63a4)

### Log output

2024-09-13 13:45:31.2138|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2024-09-13 13:45:31.2138|DEBUG|Deskband|Unhandled first chance exception|System.IO.FileNotFoundException: Nie można załadować pliku lub zestawu 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' lub jednej z jego zależności. Nie można odnaleźć określonego pliku.
Nazwa pliku: 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   w System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   w System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

OSTRZEŻENIE: rejestrowanie informacji o powiązaniach zestawów jest wyłączone.
Aby włączyć rejestrowanie błędów powiązań zestawów, ustaw wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) równą 1.
Uwaga: z włączeniem rejestrowania błędów powiązań zestawów wiąże się pewien spadek wydajności.
Aby wyłączyć tę funkcję, usuń wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog].

2024-09-13 13:45:31.2284|DEBUG|EverythingToolbar.EverythingSearch|Searching: |
2024-09-13 13:45:31.2846|DEBUG|Deskband|Unhandled first chance exception|System.ArgumentException: „-1860” jest nieprawidłową wartością dla właściwości „Width”.
   w System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
2024-09-13 13:45:31.2846|ERROR|Deskband|Unhandled exception|System.ArgumentException: „-1860” jest nieprawidłową wartością dla właściwości „Width”.
   w System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   w System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   w EverythingToolbar.SearchWindow.AnimateShow(Double left, Double top, Double width, Double height, Edge taskbarEdge) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\SearchWindow.xaml.cs:wiersz 139
   w EverythingToolbar.Behaviors.SearchWindowPlacement.OnShowing(Object sender, EventArgs e) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar.Deskband\WindowPlacement.cs:wiersz 51
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   w System.Windows.Input.InputManager.ProcessStagingArea()
   w System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   w System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   w System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   w System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   w System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   w System.Windows.UIElement.Focus()
   w EverythingToolbar.Controls.SearchBox.SelectivelyIgnoreMouseButton(Object sender, MouseButtonEventArgs e) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\Controls\SearchBox.xaml.cs:wiersz 135
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   w System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   w System.Windows.Input.InputManager.ProcessStagingArea()
   w System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   w System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   w System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   w System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
2024-09-13 13:45:32.8569|DEBUG|Deskband|Debug logging enabled.|
2024-09-13 13:45:32.8831|INFO|Deskband|EverythingToolbar 1.4.1.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-09-13 13:47:23.8875|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2024-09-13 13:47:23.8875|DEBUG|Deskband|Unhandled first chance exception|System.IO.FileNotFoundException: Nie można załadować pliku lub zestawu 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' lub jednej z jego zależności. Nie można odnaleźć określonego pliku.
Nazwa pliku: 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   w System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   w System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

OSTRZEŻENIE: rejestrowanie informacji o powiązaniach zestawów jest wyłączone.
Aby włączyć rejestrowanie błędów powiązań zestawów, ustaw wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) równą 1.
Uwaga: z włączeniem rejestrowania błędów powiązań zestawów wiąże się pewien spadek wydajności.
Aby wyłączyć tę funkcję, usuń wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog].

2024-09-13 13:47:23.9055|DEBUG|EverythingToolbar.EverythingSearch|Searching: |
2024-09-13 13:47:23.9660|DEBUG|Deskband|Unhandled first chance exception|System.ArgumentException: „-1860” jest nieprawidłową wartością dla właściwości „Width”.
   w System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
2024-09-13 13:47:23.9660|ERROR|Deskband|Unhandled exception|System.ArgumentException: „-1860” jest nieprawidłową wartością dla właściwości „Width”.
   w System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   w System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   w EverythingToolbar.SearchWindow.AnimateShow(Double left, Double top, Double width, Double height, Edge taskbarEdge) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\SearchWindow.xaml.cs:wiersz 139
   w EverythingToolbar.Behaviors.SearchWindowPlacement.OnShowing(Object sender, EventArgs e) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar.Deskband\WindowPlacement.cs:wiersz 51
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   w System.Windows.Input.InputManager.ProcessStagingArea()
   w System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   w System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   w System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   w System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   w System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   w System.Windows.UIElement.Focus()
   w EverythingToolbar.Controls.SearchBox.Focus() w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\Controls\SearchBox.xaml.cs:wiersz 101
   w EverythingToolbar.Controls.SearchBox.OnFocusRequested(Object sender, EventArgs e) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\Controls\SearchBox.xaml.cs:wiersz 41
   w System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   w NHotkey.HotkeyManagerBase.HandleHotkeyMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled, Hotkey& hotkey)
   w NHotkey.Wpf.HotkeyManager.HandleMessage(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr lparam, Boolean& handled)
   w System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
2024-09-13 13:47:25.4606|DEBUG|Deskband|Debug logging enabled.|
2024-09-13 13:47:25.4742|INFO|Deskband|EverythingToolbar 1.4.1.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-09-13 13:48:29.9759|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2024-09-13 13:48:29.9759|DEBUG|Deskband|Unhandled first chance exception|System.IO.FileNotFoundException: Nie można załadować pliku lub zestawu 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' lub jednej z jego zależności. Nie można odnaleźć określonego pliku.
Nazwa pliku: 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   w System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   w System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

OSTRZEŻENIE: rejestrowanie informacji o powiązaniach zestawów jest wyłączone.
Aby włączyć rejestrowanie błędów powiązań zestawów, ustaw wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) równą 1.
Uwaga: z włączeniem rejestrowania błędów powiązań zestawów wiąże się pewien spadek wydajności.
Aby wyłączyć tę funkcję, usuń wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog].

2024-09-13 13:48:29.9914|DEBUG|EverythingToolbar.EverythingSearch|Searching: |
2024-09-13 13:48:30.0439|DEBUG|Deskband|Unhandled first chance exception|System.ArgumentException: „-1860” jest nieprawidłową wartością dla właściwości „Width”.
   w System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
2024-09-13 13:48:30.0439|ERROR|Deskband|Unhandled exception|System.ArgumentException: „-1860” jest nieprawidłową wartością dla właściwości „Width”.
   w System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   w System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   w EverythingToolbar.SearchWindow.AnimateShow(Double left, Double top, Double width, Double height, Edge taskbarEdge) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\SearchWindow.xaml.cs:wiersz 139
   w EverythingToolbar.Behaviors.SearchWindowPlacement.OnShowing(Object sender, EventArgs e) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar.Deskband\WindowPlacement.cs:wiersz 51
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   w System.Windows.Input.InputManager.ProcessStagingArea()
   w System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   w System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   w System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   w System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   w System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   w System.Windows.UIElement.Focus()
   w EverythingToolbar.Controls.SearchBox.SelectivelyIgnoreMouseButton(Object sender, MouseButtonEventArgs e) w D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\Controls\SearchBox.xaml.cs:wiersz 135
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   w System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)
   w System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   w System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   w System.Windows.Input.InputManager.ProcessStagingArea()
   w System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   w System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   w System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   w System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
2024-09-13 13:48:31.5118|DEBUG|Deskband|Debug logging enabled.|
2024-09-13 13:48:31.5368|INFO|Deskband|EverythingToolbar 1.4.1.0 started. OS: Microsoft Windows NT 10.0.22631.0|

### Additional Information

It was working great before 1.4 update

**Comment by srwi** [comment]
Hi @kokanas, thank you for reporting the problem. It looks like this bug was introduced in 1.3.4. I implemented a fix and it will be available in the next release. I'm planning to release it rather soon.
