### ISSUE TITLE
no search results 

### ISSUE THREAD

**Issue by spaceVast** [srwi/EverythingToolbar#538]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

Version 1.5.0.0

### Everything Version

Version 1.4.1.1024 (x64)

### Windows Version

11 enterprise

### Steps to reproduce

![image](https://github.com/user-attachments/assets/ec07452c-3193-4f1a-9020-d8eb723e3c54)
![image](https://github.com/user-attachments/assets/f7e8d17e-195f-4e7d-8981-f792ea25f526)

### Expected Behavior

to get the system32 folder in the previous pics but no , didnt apear

### Actual Behavior

just strange files , no folders appear or video im searching for

### Log output

2024-09-29 12:10:22.4433|INFO|Launcher|EverythingToolbar Launcher 1.1.1.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2024-09-29 16:58:05.9884|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2024-09-29 20:34:28.5136|INFO|Launcher|EverythingToolbar 1.5.0.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2024-09-29 20:35:36.2560|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

**Comment by srwi** [comment]
Hello @spaceVast, are you able to find the System32 folder in Everything itself? In general EverythingToolbar seems to be working.

Possibly you have selected some search filters (like "match case") that prevents it from finding that folder?

**Comment by spaceVast** [comment]
Hello, no filter applied , tried restarting still the same

**Comment by srwi** [comment]
Are you able to find System32 in Everything?

**Comment by spaceVast** [comment]
i uninstalled , then reinstalled both , then worked fine after a restart
![{71AFBD1F-C736-457B-94D6-18E85C8256F1}](https://github.com/user-attachments/assets/24ea296c-69f5-4c41-b20e-22d7b674e0d3)
thanks for the help

**Comment by spaceVast** [comment]
i got the problem solved thanks for ur time
