### ISSUE TITLE
Feature Request: Light theme support

### ISSUE THREAD

**Issue by futuremotiondev** [srwi/EverythingToolbar#542]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

Love the app. Just wish there was a light mode. Any chance of this happening?

### Proposed Solution

Implementing a light theme.

### Alternatives Considered

None.

**Comment by srwi** [comment]
Hi, this is already available as a power user option and described in #508.
