### ISSUE TITLE
Feature Request: Mica doesn't match Windows 11 start menu

### ISSUE THREAD

**Issue by ak1dd** [srwi/EverythingToolbar#545]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

The mica effect looks very different to the Windows 11 default start menu.   When you click the start menu and then click the Everything Toolbar I can barely distinguish the mica effect is enabled with ET.   When I "Replace Start Menu search" the difference is jarring.   I use system dark mode and the background looks more like the background in Windows Explorer than the Start Menu.  The experience feels like two very different things...

### Proposed Solution

Match the mica opacity settings to those used by Windows Start Menu

### Alternatives Considered

Could you tweak the opacity or give us the ability to do it in the UI?

**Comment by srwi** [comment]
Yeah, it's not a perfect match. I think the Windows search doesn't actually use the Mica implementation so it will never be an exact match but you are able to tweak it slightly by changing `SearchResultsViewHeader` in `EverythingToolbar/Themes/Win11/[Dark|Light].xaml`.

Here is an example with left being the current implementation, middle as the Windows search and right being after I tried to improve it slightly with the new color value of `#c0282828`.

![grafik](https://github.com/user-attachments/assets/915cb076-a6c2-48a7-9fbf-f58786a68807)

I think the blur radius is just higher for the Windows search which I can't change when using the original Mica implementation that Windows gives me.

Please play around a little bit yourself and let me know if you can come up with a better color value. After changing the value, you need to restart EverythingToolbar. The color is in `#AARRGGBB` format.
