### ISSUE TITLE
 custom home page

### ISSUE THREAD

**Issue by ouyang7923** [srwi/EverythingToolbar#547]
### Preflight Checklist

- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same feature request without success.

### Problem Description

no problem

### Proposed Solution

There is a suggestion that if I open the everythingtoolbar interface by default, can I display my custom frequently used directory and file list, similar to the home page function in everything

### Alternatives Considered

![Snipaste_2024-11-08_11-11-20](https://github.com/user-attachments/assets/da314f86-9635-4374-beeb-efbbd0667272)
![Snipaste_2024-11-08_11-11-44](https://github.com/user-attachments/assets/001144c6-97ae-43b0-affc-65179efbfeee)
This list is displayed first each time when open "everything"

**Comment by srwi** [comment]
Hi, this has already been requested in #378.
