### ISSUE TITLE
Blank search results

### ISSUE THREAD

**Issue by 0xmbe** [srwi/EverythingToolbar#549]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.5.1.0

### Everything Version

1.4.1.1026 (x64)

### Windows Version

Windows 10 pro 19045.5011

### Steps to reproduce

I was changing settings via gui and suddenly result were blank, empty nothing.
It didn't help to remove and install again.
I had to manually delete settings.ini
Those are the settings that caused problem

FiltersPath=C:\Users\...\AppData\Roaming\Everything\Filters.csv
IconName=Icons/Dark.ico
IsTrayIconEnabled=true
LastFilter=Executable
InstanceName=EverythingToolbar.Launcher
ItemTemplate=CompactDetailed
IsThumbnailsEnabled=false
IsShowResultsCount=true
IsReplaceStartMenuSearch=false
IsShowQuickToggles=false
IsRememberFilter=true
IsUpdateNotificationsEnabled=false
IsImportFilters=false
PopupHeight=696
IsAnimationsDisabled=false

### Expected Behavior

/

### Actual Behavior

/

### Screenshots

/

### Log output

/

**Comment by srwi** [comment]
It's because of the instance name `InstanceName=EverythingToolbar.Launcher`. In most cases it should be left empty. When using Everything 1.5a or a custom named Everything instance it has to be changed accordingly.

https://www.voidtools.com/support/everything/multiple_instances/

**Comment by QuentiumYT** [comment]
I had the same issue and looked at closed issues first. Thanks for the info, that's weird that any instance name doesn't work except the blank one.
Can you edit the README to tell people to set a blank instance name?
Also what is Everything 1.5a? Latest version is 1.4.1, probably not related to the version ^^

Anyway, thanks for your amazing work, very useful tool that makes windows less bad :)

**Comment by srwi** [comment]
Thanks!

Normally the instance name should be blank by default, which is also what the standard Everything installation uses. I would assume you must have manually set it to `EverythingToolbar.Launcher` in EverythingToolbar settings. 🤷‍♂️ 

Everything 1.5a is the alpha version of Everything's next major release. Some people already use it, but it requires the user to use the non-default instance name `1.5a`.

**Comment by QuentiumYT** [comment]
Oh I see, I don't remember changing it, maybe before EverythingToolbar was a toolbar (only an app), it was different. Its name was only "Search".

That was indeed the version haha, I am not using the alpha, probably will look into that because I like cutting edge builds :) Thanks for the info
