### ISSUE TITLE
Filters-1.5a.csv was overlooked

### ISSUE THREAD

**Issue by yfdyh000** [srwi/EverythingToolbar#551]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.5.1

### Everything Version

1.5.0.1383a

### Windows Version

Win10 22H2

### Steps to reproduce

Start the searching and check the filters menu.

### Expected Behavior

The newer filters list.

### Actual Behavior

The old Filters.csv instead of Filters-1.5a.csv be used.

### Log output

N/A

**Comment by srwi** [comment]
You should be able to filter by "All files" and select the 1.5a filters that way.

Everything 1.5a won't be fully supported by EverythingToolbar while it's still in alpha.

Relevant discussion: #367
