### ISSUE TITLE
Don't be mandatory pin the app icon after Start menu replacement

### ISSUE THREAD

**Issue by yfdyh000** [srwi/EverythingToolbar#552]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.5.1

### Everything Version

1.5.0.1383a

### Windows Version

Win10 22H2

### Steps to reproduce

1. Launch the software and replace the Start menu's search from the options menu.
2. Unpin the app's taskbar icon since it is no longer necessary.

### Expected Behavior

No taskbar occupancy.

### Actual Behavior

When the program starts autonomously, it launches the setup assistant and the pin step is not skippable.

### Log output

N/A

**Comment by srwi** [comment]
Hi, in Windows 10 you would normally use the Deskband version and not the Launcher version of EverythingToolbar. If you really want to use the Launcher you should be able to just close the setup assistant to prevent it from showing up again: https://github.com/srwi/EverythingToolbar/issues/433#issuecomment-2351177810
