### ISSUE TITLE
Crash when windows RDP is connected.

### ISSUE THREAD

**Issue by YsielX** [srwi/EverythingToolbar#556]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.5.0

### Everything Version

1.4.1.1023

### Windows Version

windows 11 version 23H2

### Steps to reproduce

1. connect to Windows through RDP.
2. EverythingToolBar will crash.

### Expected Behavior

Not crash

### Actual Behavior

crashed

### Log output

2024-12-06 14:02:11.7046|ERROR|Launcher|Unhandled exception on UI thread|System.InvalidOperationException: 使用“SetterBaseCollection”之后(密封)，无法对其进行修改。
   在 System.Windows.SetterBaseCollection.CheckSealed()
   在 System.Windows.SetterBaseCollection.InsertItem(Int32 index, SetterBase item)
   在 EverythingToolbar.Controls.SearchResultsView.RegisterItemContainerStyleProperties(Object sender, ResourcesChangedEventArgs e) 位置 D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\Controls\SearchResultsView.xaml.cs:行号 46
   在 EverythingToolbar.Controls.SearchResultsView.<.ctor>b__3_0(Object s, RoutedEventArgs e) 位置 D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\Controls\SearchResultsView.xaml.cs:行号 35
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-12-06 14:02:11.7440|ERROR|Launcher|Unhandled exception|System.InvalidOperationException: 使用“SetterBaseCollection”之后(密封)，无法对其进行修改。
   在 System.Windows.SetterBaseCollection.CheckSealed()
   在 System.Windows.SetterBaseCollection.InsertItem(Int32 index, SetterBase item)
   在 EverythingToolbar.Controls.SearchResultsView.RegisterItemContainerStyleProperties(Object sender, ResourcesChangedEventArgs e) 位置 D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\Controls\SearchResultsView.xaml.cs:行号 46
   在 EverythingToolbar.Controls.SearchResultsView.<.ctor>b__3_0(Object s, RoutedEventArgs e) 位置 D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar\Controls\SearchResultsView.xaml.cs:行号 35
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   在 System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   在 MS.Internal.LoadedOrUnloadedOperation.DoWork()
   在 System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 EverythingToolbar.Launcher.Launcher.Main(String[] args) 位置 D:\a\EverythingToolbar\EverythingToolbar\EverythingToolbar.Launcher\Launcher.cs:行号 172

**Comment by srwi** [comment]
Hi @YsielX, thank you for reporting the bug. I implemented a fix which will be available in the next release!
